Vagrant.configure("2") do |config|
  config.vm.define "centos" do |nodo1|
    nodo1.vm.box = "centos-release-" + ENV['RELEASE_TO_UPGRADE']
    nodo1.ssh.private_key_path = "/home/ftsinfra/oml-boxes/centos_private_key_release-" + ENV['RELEASE_TO_UPGRADE']
    nodo1.vm.network "public_network", bridge: "enp2s0", ip: "192.168.99.63", use_dhcp_assigned_default_route: true
    nodo1.ssh.forward_agent = true
    nodo1.vm.synced_folder '.', '/vagrant', disabled: true
  end
end
