#!/bin/bash

if [ ! -z $1 ]; then
  for i in asterisk database dialer kamailio omniapp; do
    echo "$i: "
    docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $i
    docker commit $i freetechsolutions/$i:$1
    docker push freetechsolutions/$i:$1
  done
else
  echo "Falta agregar el tag con el quieres commitear/pushear"
fi
