#!/bin/bash

DOCKER_COMPOSE="`which docker-compose`"
DOCKER="`which docker`"
REPO_LOCATION="`git rev-parse --show-toplevel`"
AST_LOCATION="/opt/omnileads/asterisk"
KAM_LOCATION="/opt/omnileads/kamailio"
KAM_EXEC="$DOCKER exec -i kamailio /bin/bash -c"
AST_EXEC="$DOCKER exec -i asterisk /bin/bash -c"
DB_EXEC="$DOCKER exec -i database /bin/bash -c"
OMNIAPP_EXEC="$DOCKER exec -it -u omnileads omniapp /bin/bash -c"
CP_EXEC="$DOCKER cp omniapp:/opt/omnileads/local/oml_settings_local.py $REPO_LOCATION/ominicontacto/settings/"

if [ -z $DOCKER ];then
  echo "Docker not installed or configured, exiting"
  exit 1
elif [ -z $DOCKER_COMPOSE ]; then
  echo "Docker-compose not installed, exiting"
  exit
fi

UpCommands() {
  $AST_EXEC "if [ ! -d /var/tmp/astfiles/ ]; then mkdir /var/tmp/astfiles/; fi"
  $AST_EXEC "if [ ! -f $AST_LOCATION/etc/asterisk/oml_extensions.conf ]; then ln -s /var/tmp/astfiles/oml_extensions.conf $AST_LOCATION/etc/asterisk/oml_extensions.conf; fi"
  $AST_EXEC "if [ ! -f $AST_LOCATION/etc/asterisk/oml_extensions_sub.conf ]; then ln -s /var/tmp/astfiles/oml_extensions_sub.conf $AST_LOCATION/etc/asterisk/oml_extensions_sub.conf; fi"
  $KAM_EXEC "if [ ! -d /var/tmp/kamfiles/ ]; then mkdir /var/tmp/kamfiles/; fi"
  $KAM_EXEC "if [ ! -f $KAM_LOCATION/etc/kamailio/kamailio.cfg ]; then ln -s /var/tmp/kamfiles/kamailio.cfg $KAM_LOCATION/etc/kamailio/kamailio.cfg; fi"
  $AST_EXEC "chown -R omnileads. /opt/omnileads/asterisk/var/spool/asterisk/ && chown -R omnileads. /opt/omnileads/asterisk/etc/asterisk"
  $KAM_EXEC "chown -R omnileads. /opt/omnileads/kamailio/etc/kamailio/kamailio.cfg"
  $CP_EXEC
  $OMNIAPP_EXEC "rm -rf /opt/omnileads/local/oml_settings_local.py"
}

StartCommands() {
  $DB_EXEC "service postgresql restart"
  $KAM_EXEC "service kamailio restart"
  $AST_EXEC "service asterisk restart"
  $OMNIAPP_EXEC "DJANGO_SETTINGS_MODULE=ominicontacto.settings.develop /opt/omnileads/bin/manage.sh regenerar_asterisk"
}

RunCommands() {
  $OMNIAPP_EXEC "DJANGO_SETTINGS_MODULE=ominicontacto.settings.develop /opt/omnileads/bin/manage.sh migrate"
  $AST_EXEC "service asterisk reload"
  $OMNIAPP_EXEC "DJANGO_SETTINGS_MODULE=ominicontacto.settings.develop /opt/omnileads/bin/manage.sh collectstatic_js_reverse"
  $OMNIAPP_EXEC "DJANGO_SETTINGS_MODULE=ominicontacto.settings.develop django-server"
}

KillRun(){
  $OMNIAPP_EXEC "kill-django-server"
}
case "$1" in
  start)
    echo "Starting Omnileads containers "
    $DOCKER_COMPOSE -f devenv-stack.yml start
    StartCommands
    RunCommands
    ;;
  stop)
    echo "Stopping Omnileads containers "
    $DOCKER_COMPOSE -f devenv-stack.yml stop
    ;;
  up)
    echo "Creating and starting Omnileads containers "
    $DOCKER_COMPOSE -f devenv-stack.yml up -d
    UpCommands
    StartCommands
    RunCommands
    ;;
  down)
    echo "Stopping and killing Omnileads containers "
    $DOCKER_COMPOSE -f devenv-stack.yml down
    ;;
  run)
    RunCommands
    ;;
  killrun)
    KillRun
    ;;
  *)
    echo "Usage: /etc/init.d/docker-manage {start|stop|up|down|run|killrun}"
    exit 1
    ;;
esac
