# Generated by Django 3.2.19 on 2025-10-17 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion_telefonia_app', '0023_alter_destinoentrante_tipo'),
        ('ominicontacto_app', '0114_auto_20251016_0752'),
        ('whatsapp_app', '0014_alter_line_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaMessenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.IntegerField(choices=[(0, 'Texto')])),
                ('configuracion', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='PaginaMetaFacebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('access_token', models.CharField(max_length=500)),
                ('verify_token', models.CharField(max_length=255)),
                ('app_id', models.CharField(max_length=255)),
                ('page_id', models.CharField(max_length=255)),
                ('allow_reply_comments', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='configuracion_telefonia_app.destinoentrante')),
                ('goodbye_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pages_goodbye_message', to='whatsapp_app.plantillamensaje')),
                ('out_of_hours_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pages_out_of_hours_message', to='whatsapp_app.plantillamensaje')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='configuracion_telefonia_app.grupohorario')),
                ('welcome_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pages_welcome_message', to='whatsapp_app.plantillamensaje')),
            ],
            options={
                'verbose_name': 'Meta Page Configuration',
                'verbose_name_plural': 'Meta Page Configurations',
            },
        ),
        migrations.CreateModel(
            name='GrupoPlantillaMessenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('plantillas', models.ManyToManyField(related_name='grupos', to='facebook_meta_app.PlantillaMessenger')),
            ],
            options={
                'verbose_name': 'Grupo de Plantillas de Messenger',
                'verbose_name_plural': 'Grupos de Plantillas de Messenger',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionMetaFacebookCampana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_servicio', models.IntegerField(default=1)),
                ('campana', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_meta_facebook', to='ominicontacto_app.campana')),
                ('grupo_plantilla_facebook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuracion_facebook', to='facebook_meta_app.grupoplantillamessenger')),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campanas', to='facebook_meta_app.paginametafacebook')),
            ],
            options={
                'verbose_name': 'Configuración Meta Facebook Campaña',
                'verbose_name_plural': 'Configuraciones Meta Facebook Campaña',
            },
        ),
    ]
