# Generated by Django 3.2.19 on 2026-02-24 14:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import facebook_meta_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ominicontacto_app', '0119_merge_20260120_1051'),
        ('configuracion_telefonia_app', '0024_alter_destinoentrante_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMessengerMetaApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_client_id', models.CharField(max_length=255, null=True)),
                ('is_disposition', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expire', models.DateTimeField(null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('saliente', models.BooleanField(default=False)),
                ('atendida', models.BooleanField(default=False)),
                ('error', models.BooleanField(default=False)),
                ('error_ex', models.JSONField(default=dict)),
                ('date_last_interaction', models.DateTimeField(null=True)),
                ('client_alias', models.CharField(max_length=100, null=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations_messenger', to='ominicontacto_app.agenteprofile')),
                ('campana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messenger_conversaciones', to='ominicontacto_app.campana')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations_messenger', to='ominicontacto_app.contacto')),
                ('conversation_disposition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations_messenger', to='ominicontacto_app.historicalcalificacioncliente')),
            ],
            options={
                'verbose_name': 'Messenger Meta App Conversation',
                'verbose_name_plural': 'Messenger Meta App Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaMessenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.IntegerField(choices=[(0, 'Texto')])),
                ('configuracion', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaginaMetaFacebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('access_token', models.CharField(max_length=500)),
                ('verify_token', models.CharField(max_length=255)),
                ('app_id', models.CharField(max_length=255)),
                ('page_id', models.CharField(max_length=255)),
                ('allow_reply_comments', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='configuracion_telefonia_app.destinoentrante')),
                ('goodbye_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pages_goodbye_message', to='facebook_meta_app.plantillamessenger')),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='configuracion_telefonia_app.grupohorario')),
                ('out_of_hours_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pages_out_of_hours_message', to='facebook_meta_app.plantillamessenger')),
                ('welcome_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pages_welcome_message', to='facebook_meta_app.plantillamessenger')),
            ],
            options={
                'verbose_name': 'Meta Page Configuration',
                'verbose_name_plural': 'Meta Page Configurations',
            },
        ),
        migrations.CreateModel(
            name='OpcionMenuInteractivoMessengerMetaApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=72)),
                ('opcion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opcion_menu_messenger_meta_app', to='configuracion_telefonia_app.opciondestino')),
            ],
        ),
        migrations.CreateModel(
            name='MessageMessengerMetaApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('origen', models.CharField(max_length=100)),
                ('sender', models.JSONField(default=dict)),
                ('content', models.JSONField(default=dict)),
                ('type', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, max_length=1000, null=True, upload_to=facebook_meta_app.models.upload_to)),
                ('status', models.CharField(max_length=100)),
                ('fail_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('conversation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='facebook_meta_app.conversationmessengermetaapp')),
            ],
            options={
                'verbose_name': 'Messenger Meta App Message',
                'verbose_name_plural': 'Messenger Meta App Messages',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MenuInteractivoMessengerMetaApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_header', models.CharField(max_length=1024)),
                ('texto_opcion_incorrecta', models.CharField(blank=True, max_length=100, null=True)),
                ('texto_derivacion', models.CharField(max_length=100)),
                ('timeout', models.IntegerField(null=True)),
                ('is_main', models.BooleanField(default=False)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menuinteractivo', to='facebook_meta_app.paginametafacebook')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoPlantillaMessenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('plantillas', models.ManyToManyField(related_name='grupos', to='facebook_meta_app.PlantillaMessenger')),
            ],
            options={
                'verbose_name': 'Grupo de Plantillas de Messenger',
                'verbose_name_plural': 'Grupos de Plantillas de Messenger',
            },
        ),
        migrations.AddField(
            model_name='conversationmessengermetaapp',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='facebook_meta_app.messagemessengermetaapp'),
        ),
        migrations.AddField(
            model_name='conversationmessengermetaapp',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_messenger', to='facebook_meta_app.paginametafacebook'),
        ),
        migrations.CreateModel(
            name='ConfiguracionMetaFacebookCampana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_servicio', models.IntegerField(default=1)),
                ('campana', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_meta_facebook', to='ominicontacto_app.campana')),
                ('grupo_plantilla_facebook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuracion_facebook', to='facebook_meta_app.grupoplantillamessenger')),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campanas', to='facebook_meta_app.paginametafacebook')),
            ],
            options={
                'verbose_name': 'Configuración Meta Facebook Campaña',
                'verbose_name_plural': 'Configuraciones Meta Facebook Campaña',
            },
        ),
        migrations.CreateModel(
            name='AttachmentMessengerMetaApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='facebook_meta_app.messagemessengermetaapp')),
            ],
            options={
                'verbose_name': 'Messenger Meta App Attachment',
                'verbose_name_plural': 'Messenger Meta App Attachments',
                'ordering': ['-id'],
            },
        ),
    ]
