# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-09 21:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


def adicionar_calificacion_especial_campanas(apps, schema_editor):
    """
    Adiciona NombreCalificacion correspondiente a la Agenda.
    """
    NombreCalificacion = apps.get_model("ominicontacto_app", "NombreCalificacion")

    calificacion_agenda, _ = NombreCalificacion.objects.get_or_create(
        nombre=settings.CALIFICACION_REAGENDA)


def rollback(apps, schema_editor):
    """
    Vuelve hacia la atrás los cambios de la migración de datos especificada en la función
    'adicionar_calificacion_especial_campanas'
    """
    NombreCalificacion = apps.get_model("ominicontacto_app", "NombreCalificacion")
    NombreCalificacion.objects.get(nombre=settings.CALIFICACION_REAGENDA).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(adicionar_calificacion_especial_campanas, rollback),
    ]
