# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenteprofile',
            name='active',
        ),
        migrations.RemoveField(
            model_name='agenteprofile',
            name='name',
        ),
    ]
