# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-11-12 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0002_calificacion_especial_reagenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='dial_timeout',
            field=models.PositiveIntegerField(blank=True, default=25, null=True),
        ),
    ]
