# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-08-06 21:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0002_calificacion_especial_reagenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivodeaudio',
            name='descripcion',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[\\w]+$')]),
        ),
    ]
