# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0002_auto_20160628_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuemember',
            name='queue_name',
            field=models.ForeignKey(db_column='queue_name', on_delete=django.db.models.deletion.CASCADE, to='ominicontacto_app.Queue'),
        ),
    ]
