# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-11-22 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0003_queue_dial_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='es_originario',
            field=models.BooleanField(default=True),
        ),
    ]
