# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0003_auto_20160628_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pausa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelManagers(
            name='queuemember',
            managers=[
                ('objects_default', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='queuemember',
            unique_together=set([('queue_name', 'member')]),
        ),
    ]
