# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-08-07 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0003_auto_20180806_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grabacion',
            name='sip_agente',
        ),
        migrations.AddField(
            model_name='grabacion',
            name='agente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grabaciones', to='ominicontacto_app.AgenteProfile'),
            preserve_default=False,
        ),
    ]
