# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import ominicontacto_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0004_auto_20160629_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDatosContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('archivo_importacion', models.FileField(max_length=256, upload_to=ominicontacto_app.models.upload_to)),
                ('nombre_archivo_importacion', models.CharField(max_length=256)),
                ('metadata', models.TextField(blank=True, null=True)),
                ('sin_definir', models.BooleanField(default=True)),
                ('cantidad_contactos', models.PositiveIntegerField(default=0)),
                ('estado', models.PositiveIntegerField(choices=[(0, 'En Definici\xf3n'), (1, 'Definida'), (2, 'En Depuracion'), (3, 'Depurada')], default=0)),
            ],
        ),
    ]
