# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0004_auto_20160629_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='node_password',
            field=models.CharField(default='admin123', max_length=128),
            preserve_default=False,
        ),
    ]
