# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0004_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenteprofile',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ominicontacto_app.Grupo'),
            preserve_default=False,
        ),
    ]
