# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-11-23 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0004_contacto_es_originario'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenteencontacto',
            name='es_originario',
            field=models.BooleanField(default=True),
        ),
    ]
