# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0005_agenteprofile_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenteprofile',
            name='sip_name',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
