# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-12-04 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0006_queue_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitioexterno',
            name='metodo',
            field=models.PositiveIntegerField(choices=[(1, 'Embebido'), (2, 'Nueva pesta\xf1a')],
                                              default=1),
        ),
        migrations.AddField(
            model_name='sitioexterno',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'GET'), (2, 'POST'), (3, 'JSON')],
                                              default=1),
        ),
    ]
