# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0006_mensajeenviado_mensajerecibido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='node_password',
        ),
    ]
