# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0006_agenteprofile_sip_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenteprofile',
            name='sip_extension',
        ),
        migrations.AlterField(
            model_name='agenteprofile',
            name='sip_name',
            field=models.IntegerField(default=1000, unique=True),
            preserve_default=False,
        ),
    ]
