# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0006_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='bd_contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='ominicontacto_app.BaseDatosContacto'),
        ),
    ]
