# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 20:58
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0006_modeloenviado_modelorecibido'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='modelorecibido',
            managers=[
                ('objects_default', django.db.models.manager.Manager()),
            ],
        ),
    ]
