# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0007_auto_20160622_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenteprofile',
            old_name='sip_name',
            new_name='sip_extension',
        ),
    ]
