# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-12-26 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0007_campana_mostrar_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='oculto',
            field=models.BooleanField(default=False),
        ),
    ]
