# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0007_remove_user_node_password'),
        ('ominicontacto_app', '0007_auto_20160713_2040'),
    ]

    operations = [
    ]
