# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0008_auto_20160622_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('timeout', models.IntegerField()),
                ('retry', models.IntegerField()),
                ('maxlen', models.IntegerField()),
                ('wrapuptime', models.IntegerField()),
                ('servicelevel', models.IntegerField()),
                ('strategy', models.CharField(choices=[('ringall', 'Ringall'), ('roundrobin', 'Roundrobin'), ('leastrecent', 'Leastrecent'), ('fewestcalls', 'Fewestcalls'), ('random', 'Random'), ('rrmemory', 'Rremory')], max_length=128)),
                ('eventmemberstatus', models.BooleanField()),
                ('eventwhencalled', models.BooleanField()),
                ('weight', models.IntegerField()),
                ('ringinuse', models.BooleanField()),
                ('setinterfacevar', models.BooleanField()),
            ],
        ),
    ]
