# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0008_merge'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contacto',
            managers=[
                ('objects_default', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='auto_attend_dialer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grupo',
            name='auto_attend_ics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grupo',
            name='auto_attend_inbound',
            field=models.BooleanField(default=False),
        ),
    ]
