# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-15 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ominicontacto_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0008_formulario_oculto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenteprofile',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentes', to='ominicontacto_app.Grupo', verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='agenteprofile',
            name='modulos',
            field=models.ManyToManyField(to='ominicontacto_app.Modulo', verbose_name='M\xf3dulos'),
        ),
        migrations.AlterField(
            model_name='backlist',
            name='archivo_importacion',
            field=models.FileField(max_length=256, upload_to=ominicontacto_app.models.upload_to, verbose_name='Archivo de importaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='backlist',
            name='fecha_alta',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha alta'),
        ),
        migrations.AlterField(
            model_name='backlist',
            name='nombre',
            field=models.CharField(max_length=128, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='backlist',
            name='nombre_archivo_importacion',
            field=models.CharField(max_length=256, verbose_name='Nombre Archivo de importaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='basedatoscontacto',
            name='archivo_importacion',
            field=models.FileField(max_length=256, upload_to=ominicontacto_app.models.upload_to, verbose_name='Archivo de importaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='basedatoscontacto',
            name='fecha_alta',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha alta'),
        ),
        migrations.AlterField(
            model_name='basedatoscontacto',
            name='nombre',
            field=models.CharField(max_length=128, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='basedatoscontacto',
            name='nombre_archivo_importacion',
            field=models.CharField(max_length=256, verbose_name='Nombre Archivo de importaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='auto_attend_dialer',
            field=models.BooleanField(default=False, verbose_name='auto_attend_dialer'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='auto_attend_ics',
            field=models.BooleanField(default=False, verbose_name='auto_attend_ics'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='auto_attend_inbound',
            field=models.BooleanField(default=False, verbose_name='auto_attend_inbound'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='auto_pause',
            field=models.BooleanField(default=True, verbose_name='auto_pause'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='auto_unpause',
            field=models.PositiveIntegerField(verbose_name='auto_unpause'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nombre',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='nombre',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='nombrecalificacion',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='pausa',
            name='nombre',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='pausa',
            name='tipo',
            field=models.CharField(choices=[('P', 'Productiva'), ('R', 'Recreativa')], default='P', max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='userapicrm',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Contrase\xf1a'),
        ),
        migrations.AlterField(
            model_name='userapicrm',
            name='usuario',
            field=models.CharField(max_length=64, unique=True, verbose_name='Usuario'),
        ),
    ]
