# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0009_queue'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(max_length=128)),
                ('penalty', models.IntegerField()),
                ('paused', models.IntegerField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ominicontacto_app.AgenteProfile')),
                ('queue_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ominicontacto_app.Queue')),
            ],
        ),
    ]
