# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0009_auto_20160725_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='auto_pause',
            field=models.BooleanField(default=False),
        ),
    ]
