# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-17 17:21
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings

AGENDA = 2


def renombrar_migracion_agenda(apps, schema_editor):
    # actualiza el nombre de la calificación especial de Agenda y todas las opciones de
    # calificaciones que tienen este valor, esto se hace necesario para que no se generen dos
    # opciones de calificación para agendar después de los cambios realizados en la i18n del sistema
    OpcionCalificacion = apps.get_model('ominicontacto_app', 'OpcionCalificacion')
    OpcionCalificacion.objects.filter(tipo=AGENDA).update(nombre=settings.CALIFICACION_REAGENDA)


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0009_auto_20190115_1559'),
    ]

    operations = [
        migrations.RunPython(renombrar_migracion_agenda, reverse_code=migrations.RunPython.noop),
    ]
