# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0010_grupo_auto_pause'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'ICS'), (2, 'DIALER'), (3, 'INBOUND')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='queue',
            name='wait',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
