# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 20:02
from __future__ import unicode_literals

from django.db import migrations, models
from ominicontacto_app.models import Queue


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0011_auto_20160726_2002'),
    ]

    def forwards(self, orm):
        Queue.objects.all().delete()


