# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0011_auto_20160726_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grabacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('tipo_llamada', models.PositiveIntegerField(choices=[(1, 'ICS'), (2, 'DIALER'), (3, 'INBOUND')])),
                ('id_cliente', models.CharField(max_length=255)),
                ('tel_cliente', models.CharField(max_length=255)),
                ('grabacion', models.CharField(max_length=255)),
                ('sip_agente', models.IntegerField()),
                ('campana', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterModelManagers(
            name='queue',
            managers=[
                ('objects_default', django.db.models.manager.Manager()),
            ],
        ),
    ]
