# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0012_auto_20160727_1020'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='queue',
            managers=[
                ('objects_default', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='queue',
            name='queue_asterisk',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
