# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0012_auto_20160727_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='queue_asterisk',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grabacion',
            name='tipo_llamada',
            field=models.PositiveIntegerField(choices=[(1, 'ICS'), (2, 'DIALER'), (3, 'INBOUND'), (4, 'MANUAL')]),
        ),
    ]
