# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-02-04 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0012_parametroscrm'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacioncliente',
            name='callid',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='historicalcalificacioncliente',
            name='callid',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
