# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0013_auto_20160727_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_personal', models.BooleanField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('es_smart', models.BooleanField()),
                ('medio_comunicacion', models.PositiveIntegerField(choices=[(1, 'SMS'), (2, 'LLAMADA'), (3, 'EMAIL')])),
                ('telefono', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
                ('descripcion', models.TextField()),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ominicontacto_app.AgenteProfile')),
            ],
        ),
        migrations.AlterModelManagers(
            name='grabacion',
            managers=[
                ('objects_default', django.db.models.manager.Manager()),
            ],
        ),
    ]
