# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0014_auto_20160801_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='auto_grabacion',
            field=models.BooleanField(default=False),
        ),
    ]
