# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0015_queue_auto_grabacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.PositiveIntegerField(choices=[(1, '(en definicion)'), (2, 'Activa'), (3, 'Finalizada'), (4, 'Borrada')], default=1)),
                ('nombre', models.CharField(max_length=128)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('bd_contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campanas', to='ominicontacto_app.BaseDatosContacto')),
            ],
            managers=[
                ('objects_default', django.db.models.manager.Manager()),
            ],
        ),
    ]
