# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0016_campana'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='campana',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queue_campana', to='ominicontacto_app.Campana'),
        ),
    ]
