# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-03-20 19:56
from __future__ import unicode_literals

from django.db import migrations


def configurar_calificacion(apps, schema_editor):
    RespuestaFormularioGestion = apps.get_model("ominicontacto_app", "RespuestaFormularioGestion")
    CalificacionCliente = apps.get_model("ominicontacto_app", "CalificacionCliente")
    respuestas = RespuestaFormularioGestion.objects.all()
    for respuesta in respuestas:
        calificacion = CalificacionCliente.objects.get(
            opcion_calificacion__campana=respuesta.campana, contacto=respuesta.contacto)
        respuesta.calificacion = calificacion
        respuesta.save()


def configurar_campana_y_contacto(apps, schema_editor):
    RespuestaFormularioGestion = apps.get_model("ominicontacto_app", "RespuestaFormularioGestion")
    respuestas = RespuestaFormularioGestion.objects.all()
    for respuesta in respuestas:
        respuesta.campana = respuesta.calificacion.opcion_calificacion.campana
        respuesta.contacto = respuesta.calificacion.contacto
        respuesta.agente = respuesta.calificacion.agente
        respuesta.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0016_respuestaformulariogestion_calificacion'),
    ]

    operations = [
        migrations.RunPython(configurar_calificacion, configurar_campana_y_contacto),
    ]
