# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0017_queue_campana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuemember',
            name='queue_name',
            field=models.ForeignKey(db_column='queue_name', on_delete=django.db.models.deletion.CASCADE, related_name='queuemember', to='ominicontacto_app.Queue'),
        ),
    ]
