# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-03-21 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0017_respuestaformulariogestion_completar_calificaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestaformulariogestion',
            name='calificacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='respuesta_formulario_gestion',
                                    to='ominicontacto_app.CalificacionCliente'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='respuestaformulariogestion',
            name='campana',
        ),
        migrations.RemoveField(
            model_name='respuestaformulariogestion',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='respuestaformulariogestion',
            name='agente',
        ),
    ]
