# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-03-18 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


GESTION = 1  # Al momento de hacer esta migracion OpcionCalificacion.GESTION == 1


def asociar_formulario_de_campana_a_opcion_calificacion(apps, schema_editor):
    OpcionCalificacion = apps.get_model('ominicontacto_app', 'OpcionCalificacion')
    opciones = OpcionCalificacion.objects.filter(tipo=GESTION)
    for opcion in opciones:
        opcion.formulario = opcion.campana.formulario
        opcion.save()


def asociar_formulario_de_alguna_opcion_calificacion_a_campana(apps, schema_editor):
    """
        ATENCIÓN: Este rollback sólo garantiza que se vuelve al estado original en caso en que no
        se hayan modificado los formularios asociados a las opciones de calificación.
        La campaña quedará con UN formulario asignado a ALGUNA de las opciones de calificacion.
    """
    OpcionCalificacion = apps.get_model('ominicontacto_app', 'OpcionCalificacion')
    opciones = OpcionCalificacion.objects.filter(tipo=GESTION)
    for opcion in opciones:
        campana = opcion.campana
        campana.formulario = opcion.formulario
        campana.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0018_respuestaforumariogestion_calificacion_not_null'),
    ]

    operations = [
        # Primero agrego el campo formulario en OpcionCalificacion
        migrations.AddField(
            model_name='opcioncalificacion',
            name='formulario',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='ominicontacto_app.Formulario'),
        ),

        # Luego pongo el cada opcion de gestión el formulario de la campaña
        migrations.RunPython(asociar_formulario_de_campana_a_opcion_calificacion,
                             asociar_formulario_de_alguna_opcion_calificacion_a_campana),
    ]
