# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0018_auto_20160818_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioDemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=128, null=True)),
                ('apellido', models.CharField(blank=True, max_length=128, null=True)),
                ('telefono', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
                ('datos', models.TextField(blank=True, null=True)),
                ('extra_1', models.TextField(blank=True, null=True)),
                ('extra_2', models.CharField(blank=True, max_length=128, null=True)),
                ('extra_3', models.CharField(blank=True, max_length=128, null=True)),
                ('extra_4', models.TextField(blank=True, null=True)),
                ('extra_5', models.CharField(blank=True, max_length=128, null=True)),
                ('extra_6', models.CharField(blank=True, max_length=128, null=True)),
                ('extra_7', models.CharField(blank=True, max_length=128, null=True)),
                ('extra_8', models.CharField(blank=True, max_length=128, null=True)),
                ('extra_9', models.CharField(blank=True, max_length=128, null=True)),
                ('extra_10', models.CharField(blank=True, max_length=128, null=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios', to='ominicontacto_app.Campana')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulario_contacto', to='ominicontacto_app.Contacto')),
            ],
        ),
    ]
