# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0020_auto_20160829_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='ominicontacto_app.AgenteProfile'),
        ),
        migrations.AlterField(
            model_name='basedatoscontacto',
            name='estado',
            field=models.PositiveIntegerField(choices=[(0, 'En Definici\xf3n'), (1, 'Definida'), (2, 'En Depuracion'), (3, 'Depurada'), (4, 'Definida en actualizacion')], default=0),
        ),
    ]
