# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-05-03 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0020_remove_campana_formulario'),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemaExterno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
