# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0021_auto_20160907_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuemember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campana_member', to='ominicontacto_app.AgenteProfile'),
        ),
    ]
