# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-09 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0022_auto_20160908_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grabacion',
            name='campana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grabaciones', to='ominicontacto_app.Campana'),
        ),
    ]
