# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-05-10 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0023_agente_en_sistema_externo'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='id_externo',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='campana',
            name='sistema_externo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='campanas', to='ominicontacto_app.SistemaExterno'),
        ),
    ]
