# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-05-15 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0024_add_campana_sistema_externo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitioexterno',
            name='tipo',
        ),
        migrations.AddField(
            model_name='sitioexterno',
            name='disparador',
            field=models.PositiveIntegerField(
                choices=[(1, 'Agente'), (2, 'Autom\xe1tico'), (3, 'Servidor')], default=3),
        ),
        migrations.AddField(
            model_name='sitioexterno',
            name='formato',
            field=models.PositiveIntegerField(
                choices=[(1, 'multipart/form-data'),
                         (2, 'application/x-www-form-urlencoded'),
                         (3, 'text/plain'),
                         (4, 'application/json')],
                blank=True, null=True, default=1,
                verbose_name='Content-Type'),
        ),
        migrations.AddField(
            model_name='sitioexterno',
            name='objetivo',
            field=models.PositiveIntegerField(
                blank=True, choices=[(1, 'Embebido'), (2, 'Nueva pesta\xf1a')],
                default=1, null=True),
        ),
        migrations.AlterField(
            model_name='sitioexterno',
            name='metodo',
            field=models.PositiveIntegerField(choices=[(1, 'GET'), (2, 'POST')], default=1),
        ),
    ]
