# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-28 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0025_formulariodatoventa'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioDatoLogistica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('domicilio', models.CharField(max_length=128)),
                ('numero', models.PositiveIntegerField()),
                ('barrio', models.CharField(max_length=128)),
                ('referencia', models.CharField(max_length=128)),
                ('localidad', models.CharField(max_length=128)),
                ('horario', models.CharField(max_length=128)),
                ('dia_preferencia', models.PositiveIntegerField(choices=[(0, 'LUNES'), (1, 'MARTES'), (2, 'MIERCOLES'), (3, 'JUEVES'), (4, 'VIERNES'), (5, 'SABADO'), (6, 'DOMINGO')])),
                ('usuario', models.CharField(max_length=128)),
                ('limite', models.CharField(max_length=128)),
                ('adicional', models.CharField(max_length=128)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularioslogistica', to='ominicontacto_app.Campana')),
                ('contacto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ominicontacto_app.Contacto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulariosagente', to='ominicontacto_app.AgenteProfile')),
            ],
        ),
    ]
