# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0025_contacto_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioDatoVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=128)),
                ('depto', models.CharField(blank=True, max_length=8, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=128, null=True)),
                ('empresa_celular', models.CharField(blank=True, max_length=128, null=True)),
                ('telefono_celular', models.CharField(max_length=128)),
                ('telefono_fijo', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('nivel_estudio', models.PositiveIntegerField(blank=True, choices=[(1, 'Primario incompleto'), (2, 'Primario'), (3, 'Secuandario incompleto'), (4, 'Secundario'), (5, 'Terciario incompleto'), (6, 'Terciario'), (7, 'Universitario incompleto'), (8, 'Universitario')], null=True)),
                ('vivienda', models.PositiveIntegerField(blank=True, choices=[(1, 'Propia'), (2, 'Alquilada'), (3, 'Familia'), (4, 'Otra')], null=True)),
                ('gastos_mensuales', models.CharField(max_length=128)),
                ('nombre_padre', models.CharField(max_length=128, verbose_name='Nombre y Apellido del Padre')),
                ('nombre_madre', models.CharField(max_length=128, verbose_name='Nombre y Apellido de la Madre')),
                ('situacion_laboral', models.PositiveIntegerField(choices=[(1, 'Relacion de dependencia'), (2, 'Independiente')])),
                ('nombre_empresa', models.CharField(max_length=128, verbose_name='Nombre de la empresa')),
                ('tipo_empresa', models.PositiveIntegerField(choices=[(1, 'Pyme'), (2, 'Micro'), (3, 'Organismo Publico'), (4, 'Grande')])),
                ('domicilio_labral', models.CharField(max_length=128)),
                ('cargo', models.CharField(max_length=128, verbose_name='Cargo o Funcion')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('domicilio', models.CharField(max_length=128)),
                ('numero', models.PositiveIntegerField()),
                ('barrio', models.CharField(max_length=128)),
                ('referencia', models.CharField(max_length=128)),
                ('localidad', models.CharField(max_length=128)),
                ('horario', models.CharField(max_length=128)),
                ('dia_preferencia', models.PositiveIntegerField(choices=[(0, 'LUNES'), (1, 'MARTES'), (2, 'MIERCOLES'), (3, 'JUEVES'), (4, 'VIERNES'), (5, 'SABADO'), (6, 'DOMINGO')])),
                ('usuario', models.CharField(max_length=128)),
                ('limite', models.CharField(max_length=128)),
                ('adicional', models.CharField(max_length=128)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulariosventa', to='ominicontacto_app.Campana')),
                ('contacto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ominicontacto_app.Contacto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulariosagente', to='ominicontacto_app.AgenteProfile')),
            ],
        ),
    ]
