# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-06-06 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0025_sitio_externo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserApiCrm',
        ),
    ]
