# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-06-13 19:43
from __future__ import unicode_literals

from django.db import migrations, models


def renombrar_grupos_repetidos(apps, schema_editor):
    grupo = apps.get_model("ominicontacto_app", "Grupo")
    grupos = grupo.objects.all()
    nombres = set()
    for grupo in grupos:
        if grupo.nombre in nombres:
            # cambiar nombre
            grupo.nombre = obtener_nuevo_nombre(grupo)
            grupo.save()
        nombres.add(grupo.nombre)


def obtener_nuevo_nombre(grupo):
    grupo.nombre = grupo.nombre + ' (' + str(grupo.id) + ')'
    return grupo.nombre


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0026_delete_userapicrm'),
    ]

    operations = [
        migrations.RunPython(renombrar_grupos_repetidos, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='grupo',
            name='nombre',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nombre'),
        ),
]