# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0026_formulariodatoventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariodatoventa',
            name='localidad_entrega',
            field=models.CharField(default='Cordoba', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulariodatoventa',
            name='numero_domicilio',
            field=models.PositiveIntegerField(default=56),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formulariodatoventa',
            name='localidad',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
