# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-06-24 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0027_renombre_grupos_repetidos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupo',
            options={'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
        migrations.AlterField(
            model_name='grupo',
            name='auto_attend_dialer',
            field=models.BooleanField(default=False, verbose_name='Auto atender dailer'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='auto_attend_ics',
            field=models.BooleanField(default=False, verbose_name='Auto atender ics'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='auto_attend_inbound',
            field=models.BooleanField(default=False, verbose_name='Auto atender entrantes'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='auto_pause',
            field=models.BooleanField(default=True, verbose_name='Pausar automaticamente'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='auto_unpause',
            field=models.PositiveIntegerField(verbose_name='Despausar automaticamente'),
        ),
    ]
