# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-04 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0028_auto_20160929_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionCampana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('calificacion', models.ManyToManyField(to='ominicontacto_app.Calificacion')),
            ],
        ),
        migrations.AlterField(
            model_name='formulariodatoventa',
            name='domicilio',
            field=models.CharField(max_length=128, verbose_name='Domicilio de entrega'),
        ),
    ]
