# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-04 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0029_auto_20161004_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='calificacion_campana',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='calificacioncampana', to='ominicontacto_app.CalificacionCampana'),
            preserve_default=False,
        ),
    ]
