# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-07-03 18:56
from __future__ import unicode_literals

from django.db import migrations, models


def renombrar_BD_repetidos(apps, schema_editor):
    contactos = apps.get_model("ominicontacto_app", "BaseDatosContacto")
    basedatos = contactos.objects.all()
    nombres = set()
    for contactos in basedatos:
        if contactos.nombre in nombres:
            # cambiar nombre
            contactos.nombre = obtener_nuevo_nombre(contactos)
            contactos.save()
        nombres.add(contactos.nombre)


def obtener_nuevo_nombre(contactos):
    contactos.nombre = contactos.nombre + ' (' + str(contactos.id) + ')'
    return contactos.nombre


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0029_delete_duracion_llamada'),
    ]

    operations = [
        migrations.RunPython(renombrar_BD_repetidos, reverse_code=migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='basedatoscontacto',
            options={'verbose_name': 'Base de datos', 'verbose_name_plural': 'Base de datos'},
        ),
        migrations.AlterField(
            model_name='basedatoscontacto',
            name='nombre',
            field=models.CharField(max_length=128, unique=True, verbose_name='Nombre'),
        ),
    ]
