# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-05 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0030_campana_calificacion_campana'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_venta', models.BooleanField(default=False)),
                ('calificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ominicontacto_app.Calificacion')),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaconcliente', to='ominicontacto_app.Campana')),
                ('contacto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ominicontacto_app.Contacto')),
            ],
        ),
    ]
