# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-04 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0031_calificacioncliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenteprofile',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentes', to='ominicontacto_app.Grupo'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='auto_grabacion',
            field=models.BooleanField(default=False, verbose_name='Grabar llamados'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='maxlen',
            field=models.BigIntegerField(verbose_name='Cantidad Max de llamadas'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='retry',
            field=models.BigIntegerField(verbose_name='Tiempo de Reintento'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='servicelevel',
            field=models.BigIntegerField(verbose_name='Nivel de Servicio'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='strategy',
            field=models.CharField(choices=[('ringall', 'Ringall'), ('roundrobin', 'Roundrobin'), ('leastrecent', 'Leastrecent'), ('fewestcalls', 'Fewestcalls'), ('random', 'Random'), ('rrmemory', 'Rremory')], max_length=128, verbose_name='Estrategia de distribucion'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='timeout',
            field=models.BigIntegerField(verbose_name='Tiempo de Ring'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'ICS'), (2, 'DIALER'), (3, 'INBOUND')], verbose_name='Tipo de campa\xf1a'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='wait',
            field=models.PositiveIntegerField(verbose_name='Tiempo de espera en cola'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='weight',
            field=models.BigIntegerField(verbose_name='Importancia de campa\xf1a'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='wrapuptime',
            field=models.BigIntegerField(verbose_name='Tiempo de descanso entre llamadas'),
        ),
    ]
