# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-23 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0032_auto_20161104_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuracionDeLlamada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telefono', models.CharField(max_length=20)),
                ('fecha_hora_llamada', models.DateTimeField(auto_now=True)),
                ('tipo_llamada', models.PositiveIntegerField(choices=[(1, 'ICS'), (2, 'DIALER'), (3, 'INBOUND'), (4, 'MANUAL')])),
                ('duracion', models.TimeField()),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llamadas', to='ominicontacto_app.AgenteProfile')),
            ],
        ),
    ]
