# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-07-01 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0032_cliente_webphone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacioncliente',
            name='es_venta',
        ),
        migrations.RemoveField(
            model_name='historicalcalificacioncliente',
            name='es_venta',
        ),
    ]
