# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-29 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0033_calificacioncliente_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacioncliente',
            name='agente',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='ominicontacto_app.AgenteProfile'),
            preserve_default=False,
        ),
    ]
