# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-01-20 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0033_elimina_campo_es_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='autopause',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='queue',
            name='autopausebusy',
            field=models.BooleanField(default=False),
        ),
    ]
