# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-06 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0034_calificacioncliente_agente'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldFormulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_campo', models.CharField(max_length=64)),
                ('orden', models.PositiveIntegerField()),
                ('tipo', models.PositiveIntegerField(choices=[(1, 'Texto'), (2, 'Fecha'), (3, 'Lista')])),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='fieldformulario',
            name='formulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='ominicontacto_app.Formulario'),
        ),
    ]
