# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-13 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0034_calificacioncliente_agente'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacioncliente',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
