# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-07 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0035_auto_20161206_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldformulario',
            options={'ordering': ['orden']},
        ),
        migrations.AlterUniqueTogether(
            name='fieldformulario',
            unique_together=set([('orden', 'formulario')]),
        ),
    ]
