# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-01-24 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0036_auto_20191204_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='announce_holdtime',
            field=models.CharField(choices=[('yes', 'S\xed'), ('no', 'No'), ('once', 'Una sola vez')], default='no', max_length=128),
        ),
    ]
