# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0036_auto_20161207_1627'),
        ('ominicontacto_app', '0035_calificacioncliente_observaciones'),
    ]

    operations = [
    ]
