# Generated by Django 2.2.7 on 2020-01-28 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_telefonia_app', '0010_auto_20191203_1018'),
        ('ominicontacto_app', '0037_adiciona_campo_announce_holdtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='ivr_breakdown',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='campanas_ivr_breakdown',
                to='configuracion_telefonia_app.DestinoEntrante'),
        ),
    ]
