# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-15 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0037_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldformulario',
            name='values_select',
            field=models.TextField(blank=True, null=True),
        ),
    ]
