# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-27 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0038_fieldformulario_values_select'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.TextField()),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadataagente', to='ominicontacto_app.AgenteProfile')),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadatacliente', to='ominicontacto_app.Campana')),
                ('contacto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ominicontacto_app.Contacto')),
            ],
        ),
    ]
