# Generated by Django 2.2.7 on 2020-01-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0038_queue_ivr_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='announce_position',
            field=models.BooleanField(default=False),
        ),
    ]
