# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-02 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0039_metadatacliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='cuil',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='nombre',
        ),
    ]
