# Generated by Django 2.2.7 on 2020-01-30 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0040_elimina_modulo'),
        ('configuracion_telefonia_app', '0011_playlist_musica_de_espera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='musiconhold',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='campanas', to='configuracion_telefonia_app.Playlist'),
        ),
    ]
