# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-05 14:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0041_campana_formulario'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatacliente',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 1, 5, 14, 15, 37, 799168, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
