# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-12 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0042_metadatacliente_fecha'),
        ('ominicontacto_app', '0042_chat_mensajechat'),
    ]

    operations = [
    ]
