# Generated by Django 2.2.7 on 2020-03-19 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0042_corregir_campos_bd_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='autopause',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='autopausebusy',
        ),
    ]
