# Generated by Django 2.2.7 on 2020-04-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0043_elimina_autopause_autopausebusy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenteencontacto',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='agenteencontacto',
            name='orden',
            field=models.IntegerField(default=1),
        ),
    ]
