# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-27 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0043_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulariodemo',
            name='campana',
        ),
        migrations.RemoveField(
            model_name='formulariodemo',
            name='contacto',
        ),
        migrations.DeleteModel(
            name='FormularioDemo',
        ),
    ]
