# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-31 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0044_auto_20170127_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacioncliente',
            name='wombat_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
