# Generated by Django 2.2.7 on 2020-04-20 17:49

from django.db import migrations
from django.db.models import F


def adicionar_orden_inicial(apps, schema_editor):
    """Adiciona orden inicial a modelo AgenteEnContacto usando el id de cada objeto
    """
    AgenteEnContacto = apps.get_model("ominicontacto_app", "AgenteEnContacto")
    AgenteEnContacto.objects.update(orden=F('pk'))


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0044_agente_en_contacto_orden'),
    ]

    operations = [
        migrations.RunPython(adicionar_orden_inicial, reverse_code=migrations.RunPython.noop),
    ]
