# Generated by Django 2.2.7 on 2020-03-06 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('ominicontacto_app', '0044_crear_roles_predefinidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoOML',
            fields=[
            ],
            options={
                'verbose_name': 'permiso_oml',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.permission',),
        ),
    ]
