# Generated by Django 2.2.7 on 2020-04-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0045_datos_iniciales_orden_agente_en_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='campo_desactivacion',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
