# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-31 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0045_calificacioncliente_wombat_id'),
        ('ominicontacto_app', '0045_queue_ep_id_wombat'),
    ]

    operations = [
    ]
