# Generated by Django 2.2.7 on 2020-05-05 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0046_campana_campo_desactivacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='auto_attend_ics',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='auto_pause',
        ),
    ]
