# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-02 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0046_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldformulario',
            name='is_required',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campana',
            name='estado',
            field=models.PositiveIntegerField(choices=[(1, 'Inactiva'), (2, 'Activa'), (3, 'Finalizada'), (4, 'Borrada'), (5, 'Pausada')], default=1),
        ),
    ]
