# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-14 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0048_auto_20170213_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='oculto',
            field=models.BooleanField(default=False),
        ),
    ]
