# Generated by Django 2.2.7 on 2020-05-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0049_add_campana_outcid_outr'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='wait_announce_frequency',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
