# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-14 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0049_campana_oculto'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedatoscontacto',
            name='oculto',
            field=models.BooleanField(default=False),
        ),
    ]
