# Generated by Django 2.2.7 on 2020-05-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0050_queue_wait_announce_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='strategy',
            field=models.CharField(choices=[('rrordered', 'Rrordered'), ('leastrecent', 'Leastrecent'), ('fewestcalls', 'Fewestcalls'), ('random', 'Random'), ('rrmemory', 'Rremory')], max_length=128, verbose_name='Estrategia de distribucion'),
        ),
    ]
