# Generated by Django 2.2.7 on 2020-05-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0051_tamano_campana_campos_restriccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campana',
            name='outcid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
