# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-20 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0051_wombatlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wombatlog',
            name='agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logsaagente', to='ominicontacto_app.AgenteProfile'),
        ),
    ]
