# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-20 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0052_auto_20170220_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wombatlog',
            name='agente',
        ),
        migrations.RemoveField(
            model_name='wombatlog',
            name='campana',
        ),
        migrations.DeleteModel(
            name='WombatLog',
        ),
    ]
