# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-20 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0053_auto_20170220_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='WombatLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=128)),
                ('estado', models.CharField(max_length=128)),
                ('calificacion', models.CharField(max_length=128)),
                ('timeout', models.IntegerField()),
                ('metadata', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logsaagente', to='ominicontacto_app.AgenteProfile')),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logswombat', to='ominicontacto_app.Campana')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ominicontacto_app.Contacto')),
            ],
        ),
    ]
