# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-06 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0054_wombatlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenteprofile',
            name='estado',
            field=models.PositiveIntegerField(choices=[(1, 'OFFLINE'), (2, 'ONLINE'), (3, 'PAUSA')], default=1),
        ),
    ]
