# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-30 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0054_wombatlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queuelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('callid', models.CharField(blank=True, max_length=32, null=True)),
                ('queuename', models.CharField(blank=True, max_length=32, null=True)),
                ('campana_id', models.IntegerField(blank=True, null=True)),
                ('agent', models.CharField(blank=True, max_length=32, null=True)),
                ('agent_id', models.IntegerField(blank=True, null=True)),
                ('event', models.CharField(blank=True, max_length=32, null=True)),
                ('data1', models.CharField(blank=True, max_length=128, null=True)),
                ('data2', models.CharField(blank=True, max_length=128, null=True)),
                ('data3', models.CharField(blank=True, max_length=128, null=True)),
                ('data4', models.CharField(blank=True, max_length=128, null=True)),
                ('data5', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
