# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-06 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0055_agenteprofile_estado'),
        ('ominicontacto_app', '0055_queuelog'),
    ]

    operations = [
    ]
