# Generated by Django 2.2.7 on 2020-06-05 15:56

from django.db import migrations

from django.db.models import F


def actualizar_campo_modified_ultima_modificacion(apps, schema_editor):
    """Actualiza campo 'modified' con la fecha de la ultima modificaciones
    realizada a la calificacion final
    """
    CalificacionCliente = apps.get_model("ominicontacto_app", "CalificacionCliente")
    CalificacionCliente.objects.update(modified=F('fecha'))


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0056_adiciona_campo_modified_calificacion'),
    ]

    operations = [
        migrations.RunPython(
            actualizar_campo_modified_ultima_modificacion, reverse_code=migrations.RunPython.noop),
    ]
