# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-10 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0057_insert_trigger_queue_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='id_cliente',
        ),
    ]
