# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-12 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0058_remove_contacto_id_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulariodatoventa',
            name='campana',
        ),
        migrations.RemoveField(
            model_name='formulariodatoventa',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='formulariodatoventa',
            name='vendedor',
        ),
        migrations.DeleteModel(
            name='FormularioDatoVenta',
        ),
    ]
