# Generated by Django 2.2.7 on 2020-07-03 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0059_auditoriacalificacion_revisada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agenda',
        ),
    ]
