# Generated by Django 2.2.7 on 2020-09-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0060_delete_agenda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calificacioncliente',
            options={},
        ),
        migrations.AddIndex(
            model_name='calificacioncliente',
            index=models.Index(fields=['fecha'], name='ominicontac_fecha_4f98a8_idx'),
        ),
    ]
