# Generated by Django 2.2.7 on 2020-09-14 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0061_indice_calificacioncliente_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoBlacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=128)),
            ],
        ),
        migrations.RenameModel(
            old_name='Backlist',
            new_name='Blacklist',
        ),
        migrations.DeleteModel(
            name='ContactoBacklist',
        ),
        migrations.AddField(
            model_name='contactoblacklist',
            name='black_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactosblacklist', to='ominicontacto_app.Blacklist'),
        ),
    ]
