# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-18 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0061_insert_trigger_queue_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='gestion',
            field=models.CharField(default='Venta', max_length=128),
        ),
    ]
