# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-19 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0062_campana_gestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo_agenda', models.PositiveIntegerField(choices=[(1, 'PERSAONAL'), (2, 'GLOBAL')])),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendacontacto', to='ominicontacto_app.AgenteProfile')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ominicontacto_app.Contacto')),
            ],
        ),
    ]
