# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-25 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0063_agendacontacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendacontacto',
            name='tipo_agenda',
            field=models.PositiveIntegerField(choices=[(1, 'PERSONAL'), (2, 'GLOBAL')]),
        ),
    ]
