# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-27 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0064_auto_20170425_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacioncliente',
            name='agendado',
            field=models.BooleanField(default=False),
        ),
    ]
