# Generated by Django 2.2.7 on 2020-11-09 13:15

from django.db import migrations

from constance import config


def eliminar_puerto_setting_key_server(apps, schema_editor):
    config.KEYS_SERVER_HOST = 'https://keys-server.freetech.com.ar'


def restaurar_puerto_setting_key_server(apps, schema_editor):
    config.KEYS_SERVER_HOST = 'https://keys-server.freetech.com.ar:20852'


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0064_opcioncalificacion_ocultar'),
    ]

    operations = [
        migrations.RunPython(
            eliminar_puerto_setting_key_server, reverse_code=restaurar_puerto_setting_key_server),
    ]
