# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-28 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0065_calificacioncliente_agendado'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
