# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-10 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0067_supervisorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanaDialer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.PositiveIntegerField(choices=[(1, 'Inactiva'), (2, 'Activa'), (3, 'Finalizada'), (4, 'Borrada'), (5, 'Pausada')], default=1)),
                ('nombre', models.CharField(max_length=128)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('campaign_id_wombat', models.IntegerField(blank=True, null=True)),
                ('oculto', models.BooleanField(default=False)),
                ('gestion', models.CharField(default='Venta', max_length=128)),
                ('maxlen', models.BigIntegerField(verbose_name='Cantidad Max de llamadas')),
                ('wrapuptime', models.BigIntegerField(verbose_name='Tiempo de descanso entre llamadas')),
                ('servicelevel', models.BigIntegerField(verbose_name='Nivel de Servicio')),
                ('strategy', models.CharField(choices=[('ringall', 'Ringall'), ('roundrobin', 'Roundrobin'), ('leastrecent', 'Leastrecent'), ('fewestcalls', 'Fewestcalls'), ('random', 'Random'), ('rrmemory', 'Rremory')], max_length=128, verbose_name='Estrategia de distribucion')),
                ('eventmemberstatus', models.BooleanField()),
                ('eventwhencalled', models.BooleanField()),
                ('weight', models.BigIntegerField(verbose_name='Importancia de campa\xf1a')),
                ('ringinuse', models.BooleanField()),
                ('setinterfacevar', models.BooleanField()),
                ('wait', models.PositiveIntegerField(verbose_name='Tiempo de espera en cola')),
                ('auto_grabacion', models.BooleanField(default=False, verbose_name='Grabar llamados')),
                ('ep_id_wombat', models.IntegerField(blank=True, null=True)),
                ('bd_contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campanadialers', to='ominicontacto_app.BaseDatosContacto')),
                ('calificacion_campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificacioncampanadialer', to='ominicontacto_app.CalificacionCampana')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ominicontacto_app.Formulario')),
            ],
            managers=[
                ('objects_default', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='fieldformulario',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Texto'), (2, 'Fecha'), (3, 'Lista'), (4, 'Caja de Texto de Area')]),
        ),
    ]
