# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-11 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0068_auto_20170510_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actuacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semanal', models.PositiveIntegerField(choices=[(0, 'LUNES'), (1, 'MARTES'), (2, 'MIERCOLES'), (3, 'JUEVES'), (4, 'VIERNES'), (5, 'SABADO'), (6, 'DOMINGO')])),
                ('hora_desde', models.TimeField()),
                ('hora_hasta', models.TimeField()),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuacionesdialer', to='ominicontacto_app.CampanaDialer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
