# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-12 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0069_actuacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanaMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membername', models.CharField(max_length=128)),
                ('interface', models.CharField(max_length=128)),
                ('penalty', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')])),
                ('paused', models.IntegerField()),
            ],
            managers=[
                ('objects_default', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='campanadialer',
            name='estado',
            field=models.PositiveIntegerField(choices=[(1, 'En definicion'), (2, 'Activa'), (3, 'Finalizada'), (4, 'Borrada'), (5, 'Pausada'), (6, 'Inactiva')], default=1),
        ),
        migrations.AddField(
            model_name='campanamember',
            name='campana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='ominicontacto_app.CampanaDialer'),
        ),
        migrations.AddField(
            model_name='campanamember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanasmember', to='ominicontacto_app.AgenteProfile'),
        ),
    ]
