# Generated by Django 2.2.7 on 2021-01-05 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0070_parametroscrm_dialplan_type_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajeenviado',
            name='agente',
        ),
        migrations.DeleteModel(
            name='MensajeRecibido',
        ),
        migrations.AlterModelOptions(
            name='reglaincidenciaporcalificacion',
            options={'verbose_name': 'Regla de incidencia por calificación'},
        ),
        migrations.AlterField(
            model_name='reglaincidenciaporcalificacion',
            name='en_modo',
            field=models.PositiveIntegerField(choices=[(1, 'FIXED'), (2, 'MULT')], default=1, verbose_name='Modo'),
        ),
        migrations.AlterField(
            model_name='reglaincidenciaporcalificacion',
            name='intento_max',
            field=models.IntegerField(verbose_name='Cantidad de reintentos'),
        ),
        migrations.AlterField(
            model_name='reglaincidenciaporcalificacion',
            name='opcion_calificacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regla_incidencia', to='ominicontacto_app.OpcionCalificacion', verbose_name='Opción de calificación'),
        ),
        migrations.AlterField(
            model_name='reglaincidenciaporcalificacion',
            name='reintentar_tarde',
            field=models.IntegerField(verbose_name='Tiempo entre reintentos (seg)'),
        ),
        migrations.DeleteModel(
            name='MensajeEnviado',
        ),
    ]
