# Generated by Django 2.2.7 on 2021-01-05 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0070_parametroscrm_dialplan_type_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajeenviado',
            name='agente',
        ),
        migrations.DeleteModel(
            name='MensajeRecibido',
        ),
        migrations.DeleteModel(
            name='MensajeEnviado',
        ),
    ]
