# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-12 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0070_auto_20170511_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wombatlog',
            name='campana',
        ),
    ]
