# Generated by Django 2.2.7 on 2021-01-18 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0071_auto_20210105_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='audio_previo_conexion_llamada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queues_anuncio_entrada', to='ominicontacto_app.ArchivoDeAudio'),
        ),
    ]
