# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-12 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0074_delete_objects_wombatlog_calificacion_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='wombatlog',
            name='campana',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logswombat', to='ominicontacto_app.CampanaDialer'),
            preserve_default=False,
        ),
    ]
