# Generated by Django 2.2.7 on 2021-04-11 14:19

from django.db import migrations, models
import django.db.models.deletion
import ominicontacto_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0075_historicalrespuestaformulariogestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListasRapidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, unique=True, verbose_name='Nombre')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha alta')),
                ('archivo_importacion', models.FileField(max_length=256, upload_to=ominicontacto_app.models.upload_to, verbose_name='Archivo de importación')),
                ('nombre_archivo_importacion', models.CharField(max_length=256, verbose_name='Nombre Archivo de importación')),
                ('cantidad_contactos', models.PositiveIntegerField(default=0)),
                ('metadata', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactoListaRapida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=128)),
                ('nombre', models.CharField(max_length=128)),
                ('lista_rapida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactoslistarapida', to='ominicontacto_app.ListasRapidas')),
            ],
        ),
    ]
