# Generated by Django 2.2.7 on 2021-04-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0076_contactolistarapida_listasrapidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='speech',
            field=models.TextField(blank=True, null=True),
        ),
    ]
