# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-15 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0077_calificacioncliente_campana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='type',
        ),
    ]
