# Generated by Django 2.2.7 on 2021-04-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0077_adiciona_speech_campana'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='acceso_grabaciones_agente',
            field=models.BooleanField(default=True, verbose_name='Acceso grabaciones agentes'),
        ),
    ]
