# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-15 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0078_remove_queue_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campana',
            name='campaign_id_wombat',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='ep_id_wombat',
        ),
    ]
