# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-15 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0080_campanamember_campana_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActuacionVigente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domingo', models.BooleanField()),
                ('lunes', models.BooleanField()),
                ('martes', models.BooleanField()),
                ('miercoles', models.BooleanField()),
                ('jueves', models.BooleanField()),
                ('viernes', models.BooleanField()),
                ('sabado', models.BooleanField()),
                ('hora_desde', models.TimeField()),
                ('hora_hasta', models.TimeField()),
                ('campana', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ominicontacto_app.CampanaDialer')),
            ],
        ),
    ]
