# Generated by Django 2.2.7 on 2021-07-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0080_adiciona_positiva_opcion_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='on_hold',
            field=models.BooleanField(default=True, verbose_name='On-Hold'),
        ),
    ]
