# Generated by Django 2.2.7 on 2021-11-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0081_adiciona_on_hold_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='cantidad_agendas_personales',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad agendas personales'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='limitar_agendas_personales',
            field=models.BooleanField(default=False, verbose_name='Limitar agendas personales'),
        ),
    ]
