# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-15 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0081_actuacionvigente'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='auto_unpause',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
