# Generated by Django 2.2.7 on 2022-01-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0082_grupo_limitar_agendas_personales'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='limitar_agendas_personales_en_dias',
            field=models.BooleanField(default=False, verbose_name='Limitar agendas personales en días'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='tiempo_maximo_para_agendar',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tiempo máximo para agendar'),
        ),
    ]
