# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-17 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0083_backlist_contactobacklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitioExterno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=256)),
            ],
        ),
    ]
