# Generated by Django 2.2.7 on 2022-01-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0083_grupo_limitar_agendas_personales_en_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='obligar_despausa',
            field=models.BooleanField(default=False, verbose_name='Forzar Despausa'),
        ),
    ]
