# Generated by Django 2.2.7 on 2022-02-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0084_grupo_obligar_despausa'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación'),
        ),
        migrations.AlterField(
            model_name='contactoblacklist',
            name='telefono',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
