# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-17 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0084_sitioexterno'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanadialer',
            name='sitio_externo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ominicontacto_app.SitioExterno'),
        ),
    ]
