# Generated by Django 2.2.7 on 2022-02-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0085_auto_20220203_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='show_console_timers',
            field=models.BooleanField(default=True, verbose_name='Ver temporizadores en consola'),
        ),
    ]
