# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-18 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0085_campanadialer_sitio_externo'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanadialer',
            name='tipo_interaccion',
            field=models.PositiveIntegerField(choices=[(1, 'Formulario'), (2, 'Url externa')], default=1),
        ),
    ]
