# Generated by Django 2.2.7 on 2022-02-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0086_grupo_show_console_timers'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='acceso_agendas_agente',
            field=models.BooleanField(default=True, verbose_name='Acceso a las agendas como agente'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='acceso_calificaciones_agente',
            field=models.BooleanField(default=True, verbose_name='Acceso a las calificaciones como agente'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='acceso_campanas_preview_agente',
            field=models.BooleanField(default=True, verbose_name='Acceso a las campañas preview como agente'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='acceso_contactos_agente',
            field=models.BooleanField(default=True, verbose_name='Acceso a los contactos como agente'),
        ),
    ]
