# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-18 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0086_campanadialer_tipo_interaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanadialer',
            name='formulario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ominicontacto_app.Formulario'),
        ),
    ]
