# Generated by Django 2.2.7 on 2022-02-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0088_opcioncalificacion_interaccion_crm'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='campo_direccion',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
