# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-22 17:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0088_reglasincidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanadialer',
            name='reported_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
