# Generated by Django 2.2.7 on 2022-04-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0090_campana_mostrar_did_nombre_ruta_entrante'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacioncliente',
            name='tipo_agenda',
            field=models.PositiveIntegerField(choices=[(1, 'PERSONAL'), (2, 'GLOBAL')], null=True),
        ),
        migrations.AddField(
            model_name='historicalcalificacioncliente',
            name='tipo_agenda',
            field=models.PositiveIntegerField(choices=[(1, 'PERSONAL'), (2, 'GLOBAL')], null=True),
        ),
    ]
