# Generated by Django 2.2.7 on 2022-04-11 23:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0091_calificacioncliente_tipo_agenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConjuntoDePausa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionDePausa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_to_end_pause', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(28800)])),
                ('conjunto_de_pausa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pausas', to='ominicontacto_app.ConjuntoDePausa', verbose_name='Conjunto De Pausas')),
                ('pausa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones', to='ominicontacto_app.Pausa', verbose_name='Pausa')),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='conjunto_de_pausa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos', to='ominicontacto_app.ConjuntoDePausa'),
        ),
    ]
