# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-24 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0093_campana_campaign_id_wombat'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='ep_id_wombat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
