# Generated by Django 2.2.7 on 2022-04-26 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0093_campana_control_de_duplicados'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='prioridad',
            field=models.PositiveIntegerField(
                default=10, validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100)]),
        ),
    ]
