# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-24 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0094_queue_ep_id_wombat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='retry',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Tiempo de Reintento'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='timeout',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Tiempo de Ring'),
        ),
    ]
