# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-24 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0095_auto_20170524_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Entrante'), (2, 'Dialer')], default=1),
            preserve_default=False,
        ),
    ]
