# Generated by Django 2.2.7 on 2022-05-27 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0095_sitio_externo_actualizar_validaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenteensistemaexterno',
            name='agente',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sistemas_externos',
                to='ominicontacto_app.AgenteProfile'),
        ),
        migrations.AlterField(
            model_name='agenteensistemaexterno',
            name='sistema_externo',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='agentes_en_sistema',
                to='ominicontacto_app.SistemaExterno'),
        ),
    ]
