# Generated by Django 2.2.7 on 2022-07-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0096_agenteensistemaexterno_related_names'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='historicalrespuestaformulariogestion',
            index=models.Index(fields=['history_change_reason'],
                               name='histresp_hist_chg_reason_idx')
        ),
    ]
