# Generated by Django 2.2.7 on 2022-06-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0096_agenteensistemaexterno_related_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='nombre',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
