# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-25 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0096_campana_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='sitio_externo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ominicontacto_app.SitioExterno'),
        ),
        migrations.AddField(
            model_name='campana',
            name='tipo_interaccion',
            field=models.PositiveIntegerField(choices=[(1, 'Formulario'), (2, 'Url externa')], default=1),
        ),
    ]
