# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-25 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0097_auto_20170525_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campana',
            name='formulario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ominicontacto_app.Formulario'),
        ),
    ]
