# Generated by Django 2.2.7 on 2022-09-15 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0098_autenticacion_sitio_externo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='ivr_breakdown',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='campanas_ivr_breakdown',
                                    to='configuracion_telefonia_app.DestinoEntrante'),
        ),
    ]
