# Generated by Django 2.2.7 on 2022-11-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0098_autenticacion_sitio_externo'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='campos_bd_obligatorios',
            field=models.CharField(default='', max_length=2052),
        ),
    ]
