# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-26 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0100_delete_objects_actuacion_reglas'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuacionvigente',
            name='campana',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ominicontacto_app.Campana'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reglasincidencia',
            name='campana',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reglas_incidencia', to='ominicontacto_app.Campana'),
            preserve_default=False,
        ),
    ]
