# Generated by Django 2.2.7 on 2022-07-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0100_queue_ivr_breakdown_on_delete'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='historicalcalificacioncliente',
            index=models.Index(fields=['modified'],
                               name='histcalifcli_hist_modified_idx')
        ),
    ]
