# Generated by Django 2.2.7 on 2023-01-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0100_queue_ivr_breakdown_on_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='whatsapp_habilitado',
            field=models.BooleanField(default=False),
        ),
    ]
