# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-29 18:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0101_auto_20170526_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='reported_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campana',
            name='estado',
            field=models.PositiveIntegerField(choices=[(1, 'En definicion'), (2, 'Activa'), (3, 'Finalizada'), (4, 'Borrada'), (5, 'Pausada'), (6, 'Inactiva')], default=1),
        ),
    ]
