# Generated by Django 2.2.7 on 2023-09-15 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0101_historicalcalificacioncliente_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutenticacionExternaDeUsuario',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='autenticacionexternadeusuario',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='autenticacion_externa', to=settings.AUTH_USER_MODEL),
        ),
    ]
