# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-30 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0102_auto_20170529_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campana',
            name='nombre',
        ),
    ]
