# Generated by Django 2.2.7 on 2023-01-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0102_autenticacion_externa_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='whatsapp_habilitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grupo',
            name='whatsapp_habilitado',
            field=models.BooleanField(default=False,
                                      verbose_name='Permiso de uso de la canalidad WhatsApp'),
        ),
    ]
