# Generated by Django 3.2.19 on 2024-06-07 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0103_whatsapp_configuracion_y_canalidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcalificacioncliente',
            options={'get_latest_by': ('history_date', 'history_id'),
                     'ordering': ('-history_date', '-history_id'),
                     'verbose_name': 'historical calificacion cliente',
                     'verbose_name_plural': 'historical calificacion clientes'},
        ),
        migrations.AlterModelOptions(
            name='historicalrespuestaformulariogestion',
            options={'get_latest_by': ('history_date', 'history_id'),
                     'ordering': ('-history_date', '-history_id'),
                     'verbose_name': 'historical respuesta formulario gestion',
                     'verbose_name_plural': 'historical respuesta formulario gestions'},
        ),
        migrations.AlterField(
            model_name='grupo',
            name='conjunto_de_pausa',
            field=models.ForeignKey(blank=True,
                                    null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='grupos',
                                    to='ominicontacto_app.conjuntodepausa',
                                    verbose_name='Conjunto de pausas'),  # VERBOSE NAME
        ),
        migrations.AlterField(
            model_name='historicalcalificacioncliente',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalrespuestaformulariogestion',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='monitor_join',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='reportholdtime',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='timeoutrestart',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
