# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-30 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0103_delete_objects_campana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campana',
            name='nombre',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
