# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-30 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0104_delete_objects_campana'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='nombre',
            field=models.CharField(default='campana', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
