# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-02 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0105_agenteprofile_reported_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actuacion',
            name='campana',
        ),
        migrations.DeleteModel(
            name='Actuacion',
        ),
    ]
