# Generated by Django 3.2.19 on 2024-08-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0105_queue_strategy_ringall'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='permitir_llamadas_manuales_a_dialer',
            field=models.BooleanField(default=False, verbose_name='Campañas Dialer'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='permitir_llamadas_manuales_a_entrante',
            field=models.BooleanField(default=False, verbose_name='Campañas Entrante'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='permitir_llamadas_manuales_a_manuales',
            field=models.BooleanField(default=False, verbose_name='Campañas Manuales'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='permitir_llamadas_manuales_a_preview',
            field=models.BooleanField(default=False, verbose_name='Campañas Preview'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='restringir_tipo_llamadas_manuales',
            field=models.BooleanField(default=False,
                                      verbose_name='Restringir tipo de llamadas manuales'),
        ),
    ]
