# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-02 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0106_auto_20170602_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campanamember',
            name='campana',
        ),
        migrations.RemoveField(
            model_name='campanamember',
            name='member',
        ),
        migrations.DeleteModel(
            name='CampanaMember',
        ),
    ]
