# Generated by Django 3.2.19 on 2024-09-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0106_restringir_llamadas_manuales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldformulario',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Texto'), (2, 'Fecha'), (3, 'Lista'), (4, 'Caja de Texto de Area'), (5, 'Número')]),
        ),
        migrations.AddField(
            model_name='fieldformulario',
            name='cifras_significativas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldformulario',
            name='tipo_numero',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'ENTERO'), (2, 'DECIMAL')], null=True),
        ),
    ]
