# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-02 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0107_auto_20170602_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campanadialer',
            name='bd_contacto',
        ),
        migrations.RemoveField(
            model_name='campanadialer',
            name='calificacion_campana',
        ),
        migrations.RemoveField(
            model_name='campanadialer',
            name='formulario',
        ),
        migrations.RemoveField(
            model_name='campanadialer',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='campanadialer',
            name='sitio_externo',
        ),
        migrations.DeleteModel(
            name='CampanaDialer',
        ),
    ]
