# Generated by Django 3.2.19 on 2025-01-21 12:16

from django.db import migrations, models
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0107_add_tipo_numero_fieldformulario'),
    ]

    operations = [
         migrations.AddField(
            model_name='fieldformulario',
            name='sitio_externo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ominicontacto_app.sitioexterno', blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldformulario',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Texto'), (2, 'Fecha'), (3, 'Lista'), (4, 'Caja de Texto de Area'), (5, 'Número'), (6, 'Lista Dinámica')]),
        ),
        migrations.AlterField(
            model_name='sitioexterno',
            name='disparador',
            field=models.PositiveIntegerField(choices=[(1, 'Agente'), (2, 'Automático'), (3, 'Servidor'), (4, 'Calificación'), (5, 'Lista Dinámica')], default=3),
        ),
    ]
