# Generated by Django 3.2.19 on 2025-02-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0108_add_sitio_externo_fieldformulario'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacioncliente',
            name='subcalificacion',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalcalificacioncliente',
            name='subcalificacion',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nombrecalificacion',
            name='subcalificaciones',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AddField(
            model_name='opcioncalificacion',
            name='subcalificaciones',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
