# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-05 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0108_auto_20170602_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='detectar_contestadores',
            field=models.BooleanField(default=False),
        ),
    ]
