# Generated by Django 3.2.19 on 2025-03-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0109_auto_20250224_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendacontacto',
            name='telefono',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
