# Generated by Django 3.2.19 on 2024-12-03 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_telefonia_app', '0021_alter_destinoentrante_tipo'),
        ('ominicontacto_app', '0110_add_telefono_agendacontacto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='destino',
            new_name='destino_failover',
        ),
        migrations.AddField(
            model_name='queue',
            name='destino_dialer',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='campanas_destino_dialer',
                                    to='configuracion_telefonia_app.destinoentrante'),
        ),
    ]
