# Generated by Django 3.2.19 on 2025-08-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0111_calificaciontelefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='permitir_calificar_telefonos',
            field=models.BooleanField(default=False),
        ),
    ]
