# Generated by Django 3.2.19 on 2025-07-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0111_campana_destino_dialer'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='acceso_cambiar_contrasena_agente',
            field=models.BooleanField(default=True, verbose_name='Acceso a cambiar la contraseña como agente'),
        ),
    ]
