# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-08 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0111_userapicrm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapicrm',
            name='usuario',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
