# Generated by Django 3.2.19 on 2025-08-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0112_campana_permitir_calificar_telefonos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciontelefono',
            name='calificacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcalificaciontelefono',
            name='calificacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
