# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-09 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0112_auto_20170608_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorprofile',
            name='is_administrador',
            field=models.BooleanField(default=False),
        ),
    ]
