# Generated by Django 3.2.19 on 2025-08-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0112_auto_20250721_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='mostrar_callid',
            field=models.BooleanField(default=False),
        )
    ]
