# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-16 18:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0113_supervisorprofile_is_administrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='supervisors',
            field=models.ManyToManyField(related_name='campanasupervisors', to=settings.AUTH_USER_MODEL),
        ),
    ]
