# Generated by Django 3.2.19 on 2025-10-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0113_add_mostrar_callid'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='meta_facebook_habilitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grupo',
            name='meta_facebook_habilitado',
            field=models.BooleanField(default=False, verbose_name='Permiso de uso de la canalidad Meta Facebook'),
        ),
    ]
