# Generated by Django 3.2.19 on 2025-08-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0113_add_mostrar_callid'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='call_another_agent',
            field=models.BooleanField(default=False, verbose_name='Llamar a otro agente'),
        ),
    ]
