# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-23 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0114_campana_supervisors'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='es_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campana',
            name='estado',
            field=models.PositiveIntegerField(choices=[(1, 'En definicion'), (2, 'Activa'), (3, 'Finalizada'), (4, 'Borrada'), (5, 'Pausada'), (6, 'Inactiva'), (7, '(Template en definicion)'), (8, 'Template Activo'), (9, 'Template Borrado')], default=1),
        ),
    ]
