# Generated by Django 3.2.19 on 2025-08-27 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0114_add_call_another_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='permitir_calificar_telefonos',
            field=models.BooleanField(blank=True, default=False)
        ),
        migrations.CreateModel(
            name='CalificacionTelefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.CharField(blank=True, max_length=200, null=True)),
                ('campo_contacto', models.CharField(max_length=200)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_telefonos', to='ominicontacto_app.agenteprofile')),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ominicontacto_app.campana')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ominicontacto_app.contacto')),
            ],
            options={
                'unique_together': {('campana', 'contacto', 'campo_contacto')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalCalificacionTelefono',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('fecha', models.DateTimeField(blank=True, editable=False)),
                ('calificacion', models.CharField(blank=True, max_length=200, null=True)),
                ('campo_contacto', models.CharField(max_length=200)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('agente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ominicontacto_app.agenteprofile')),
                ('campana', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ominicontacto_app.campana')),
                ('contacto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ominicontacto_app.contacto')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical calificacion telefono',
                'verbose_name_plural': 'historical calificacion telefonos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
