# Generated by Django 3.2.19 on 2025-12-15 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0114_auto_20251016_0752'),
        ('ominicontacto_app', '0115_calificacion_telefono'),
    ]

    operations = [
    ]
