# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-23 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0115_auto_20170623_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='nombre_template',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
