# Generated by Django 3.2.19 on 2025-12-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0116_merge_20251215_0539'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='historicalcalificacioncliente',
            name='histcalifcli_hist_modified_idx',
        ),
        migrations.RemoveIndex(
            model_name='historicalrespuestaformulariogestion',
            name='histresp_hist_chg_reason_idx',
        ),
        migrations.AlterField(
            model_name='nombrecalificacion',
            name='subcalificaciones',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='opcioncalificacion',
            name='subcalificaciones',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
