# Generated by Django 3.2.19 on 2026-02-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0116_queue_transcription_resume_percentage'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='historicalcalificacioncliente',
            name='histcalifcli_hist_modified_idx',
        ),
        migrations.RemoveIndex(
            model_name='historicalrespuestaformulariogestion',
            name='histresp_hist_chg_reason_idx',
        ),
        migrations.AddField(
            model_name='campana',
            name='meta_facebook_habilitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contacto',
            name='facebook',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='grupo',
            name='meta_facebook_habilitado',
            field=models.BooleanField(default=False, verbose_name='Permiso de uso de la canalidad Meta Facebook'),
        ),
        migrations.AlterField(
            model_name='calificacioncliente',
            name='canalidad',
            field=models.PositiveIntegerField(choices=[(0, 'Teléfono'), (1, 'Whatsapp'), (2, 'Facebook')], default=0),
        ),
        migrations.AlterField(
            model_name='historicalcalificacioncliente',
            name='canalidad',
            field=models.PositiveIntegerField(choices=[(0, 'Teléfono'), (1, 'Whatsapp'), (2, 'Facebook')], default=0),
        ),
        migrations.AlterField(
            model_name='nombrecalificacion',
            name='subcalificaciones',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='opcioncalificacion',
            name='subcalificaciones',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
