# Generated by Django 3.2.19 on 2025-12-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0117_auto_20251215_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='facebook',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='calificacioncliente',
            name='canalidad',
            field=models.PositiveIntegerField(choices=[(0, 'Teléfono'), (1, 'Whatsapp'), (2, 'Facebook')], default=0),
        ),
        migrations.AlterField(
            model_name='historicalcalificacioncliente',
            name='canalidad',
            field=models.PositiveIntegerField(choices=[(0, 'Teléfono'), (1, 'Whatsapp'), (2, 'Facebook')], default=0),
        ),
    ]
