# Generated by Django 3.2.19 on 2026-01-20 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0116_queue_transcription_resume_percentage'),
        ('ominicontacto_app', '0118_auto_20251230_1240'),
    ]

    operations = [
    ]
