# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-01 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0119_update_procedimiento_insert_trigger_queue_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='es_manual',
            field=models.BooleanField(default=False),
        ),
    ]
