# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-01 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0120_queuemember_id_campana'),
        ('ominicontacto_app', '0120_campana_es_manual'),
    ]

    operations = [
    ]
