# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-02 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0121_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionManual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=128)),
                ('es_gestion', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('wombat_id', models.IntegerField()),
                ('agendado', models.BooleanField(default=False)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificacionesmanuales', to='ominicontacto_app.AgenteProfile')),
                ('calificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ominicontacto_app.Calificacion')),
            ],
        ),
        migrations.AlterField(
            model_name='campana',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Entrante'), (2, 'Dialer'), (3, 'Manual')]),
        ),
        migrations.AddField(
            model_name='calificacionmanual',
            name='campana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificacionmanual', to='ominicontacto_app.Campana'),
        ),
    ]
