# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-08 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0124_calificacionmanual_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenteprofile',
            name='is_inactive',
            field=models.BooleanField(default=False),
        ),
    ]
