# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-18 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0125_agenteprofile_is_inactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaManual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=128)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo_agenda', models.PositiveIntegerField(choices=[(1, 'PERSONAL'), (2, 'GLOBAL')])),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamanual', to='ominicontacto_app.AgenteProfile')),
            ],
        ),
    ]
