# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-18 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0126_agendamanual'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='objetivo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
