# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-02 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0127_campana_objetivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrabacionMarca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('uid', models.CharField(max_length=45)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'ominicontacto_app_grabacion_marca',
            },
        ),
        migrations.AddField(
            model_name='grabacion',
            name='uid',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
