# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-28 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0127_campana_objetivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrabacionMarca',
            fields=[
                ('grabacion', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                    to='ominicontacto_app.Grabacion')),
                ('uid', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'ominicontacto_app_grabacion_marca',
            },
        ),
    ]
