# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-10 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0128_grabacionmarca'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteEnContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('estado', models.PositiveIntegerField(
                    choices=[(1, 'ENTREGADO'), (2, 'ATENDIENDO'), (3, 'FINALIZADO')])),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             to='ominicontacto_app.AgenteProfile')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               to='ominicontacto_app.Contacto')),
            ],
        ),
        migrations.AddField(
            model_name='contacto',
            name='contactantes_preview',
            field=models.ManyToManyField(through='ominicontacto_app.AgenteEnContacto',
                                         to='ominicontacto_app.AgenteProfile'),
        ),
    ]
