# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-11 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0128_grabacionmarca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campana',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Entrante'), (2, 'Dialer'),
                                                       (3, 'Manual'), (4, 'Preview')]),
        ),
    ]
