# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-20 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0129_auto_20171011_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteEnContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('agente_id', models.IntegerField()),
                ('contacto_id', models.IntegerField()),
                ('datos_contacto', models.TextField()),
                ('telefono_contacto', models.CharField(max_length=128)),
                ('campana_id', models.IntegerField()),
                ('estado', models.PositiveIntegerField(choices=[(1, 'ENTREGADO'), (2, 'ATENDIENDO'),
                                                                (3, 'FINALIZADO')])),
            ],
        ),
    ]
