# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-21 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0131_auto_20171025_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenteencontacto',
            name='modificado',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
