# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-05 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0132_agenteencontacto_modificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenteencontacto',
            name='estado',
            field=models.PositiveIntegerField(
                choices=[(0, 'INICIAL'), (1, 'ENTREGADO'), (2, 'FINALIZADO')]),
        ),
    ]
