# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-21 13:22
from __future__ import unicode_literals

from django.db import migrations


def adicionar_tipo_campana_queuelog(apps, schema_editor):
    """
    Adiciona información sobre el tipo de campaña en las entradas del modelo
    Queuelog
    """
    Queuelog = apps.get_model("ominicontacto_app", "queuelog")
    Campana = apps.get_model("ominicontacto_app", "campana")

    # Creamos un diccionario con los ids de las campañas y su tipo
    # para optimizar queries
    campana_type_dict = {}
    for campana in Campana.objects_default.all():
        campana_type_dict[campana.pk] = campana.type

    # copiamos la info del tipo de campaña en las entradas del modelo Queuelog
    for queue_log in Queuelog.objects.all():
        campana_id = queue_log.campana_id
        if campana_id != -1:
            queue_log.data5 = campana_type_dict[campana_id]
            queue_log.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0133_auto_20171205_0952'),
    ]

    operations = [
        migrations.RunPython(adicionar_tipo_campana_queuelog),
    ]
