# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-20 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager
import ominicontacto_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0133_auto_20171205_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoDeAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('audio_original', models.FileField(blank=True, null=True, upload_to=ominicontacto_app.models.upload_to_audio_original)),
                ('audio_asterisk', models.FileField(blank=True, null=True, upload_to=ominicontacto_app.models.upload_to_audio_asterisk)),
                ('borrado', models.BooleanField(default=False, editable=False)),
            ],
            managers=[
                ('objects_default', django.db.models.manager.Manager()),
            ],
        ),
    ]
