# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-22 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0134_archivodeaudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grabacion',
            name='tipo_llamada',
            field=models.PositiveIntegerField(
                choices=[(1, 'ICS'), (2, 'DIALER'), (3, 'INBOUND'), (4, 'MANUAL'), (5, 'PREVIEW')]),
        ),
    ]
