# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-21 13:22
from __future__ import unicode_literals

from django.db import migrations


def adicionar_tipo_campana_queuelog(apps, schema_editor):
    """
    Esta migración queda reemplazada por la nueva migración 0144
    """
    pass


def rollback(apps, schema_editor):
    """
    Esta migración queda reemplazada por la nueva migración 0144
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0135_auto_20171222_1726'),
    ]

    operations = [
        migrations.RunPython(adicionar_tipo_campana_queuelog, rollback),
    ]
