# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-27 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0136_adicionar_tipo_campana_queuelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='audio_para_contestadores',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ominicontacto_app.ArchivoDeAudio'),
        ),
    ]
