# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-02 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0137_queue_audio_para_contestadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='pausa',
            name='tipo',
            field=models.CharField(choices=[('P', 'Productiva'), ('R', 'Recreativa')], default='P', max_length=1),
        ),
    ]
