# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-29 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0137_queue_audio_para_contestadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='audio_de_ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queues_ingreso', to='ominicontacto_app.ArchivoDeAudio'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='audio_para_contestadores',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queues_contestadores', to='ominicontacto_app.ArchivoDeAudio'),
        ),
    ]
