# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-29 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0138_auto_20171229_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacioncliente',
            name='calificacion',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE,
                to='ominicontacto_app.Calificacion'),
        ),
    ]
