# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-09 21:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


def adicionar_calificacion_especial_campanas(apps, schema_editor):
    """
    Adiciona una calificación especial de sistema para designar la agenda
    de un contacto en una calificación a cada una de las calificaciones
    asociadas a una campaña
    """
    Campana = apps.get_model("ominicontacto_app", "campana")
    Calificacion = apps.get_model("ominicontacto_app", "calificacion")

    calificacion_agenda, _ = Calificacion.objects.get_or_create(
        nombre=settings.CALIFICACION_REAGENDA)

    for campana in Campana.objects_default.all():
        campana.calificacion_campana.calificacion.add(calificacion_agenda)


def rollback(apps, schema_editor):
    """
    Vuelve hacia la atrás los cambios de la migración de datos especificada en la función
    'adicionar_calificacion_especial_campanas'
    """
    Calificacion = apps.get_model("ominicontacto_app", "calificacion")
    Calificacion.objects.filter(nombre=settings.CALIFICACION_REAGENDA).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0139_auto_20171229_1222'),
    ]

    operations = [
        migrations.RunPython(adicionar_calificacion_especial_campanas, rollback),
    ]
