# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-03 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0139_auto_20171229_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='pausa',
            name='eliminada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pausa',
            name='tipo',
            field=models.CharField(choices=[('P', 'Productiva'), ('R', 'Recreativa')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='pausa',
            name='nombre',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
