# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-04 13:00
from __future__ import unicode_literals

from django.db import migrations


def cambiar_nombres_a_ids_de_pausas(apps, schema_editor):
    Pausa = apps.get_model("ominicontacto_app", "Pausa")
    Queuelog = apps.get_model("ominicontacto_app", "Queuelog")
    db_alias = schema_editor.connection.alias
    pausas = Pausa.objects.using(db_alias).all()
    acw_logs = Queuelog.objects.using(db_alias).filter(event__in=['PAUSEALL', 'PAUSE'], data1='ACW')
    acw_logs.update(data1='0')
    for pausa in pausas:
        nombre = pausa.nombre.upper()
        logs = Queuelog.objects.using(db_alias).filter(event__in=['PAUSEALL', 'PAUSE'],
                                                       data1=nombre)
        logs.update(data1=str(pausa.id))


def cambiar_ids_a_nombres_de_pausas(apps, schema_editor):
    Pausa = apps.get_model("ominicontacto_app", "Pausa")
    Queuelog = apps.get_model("ominicontacto_app", "Queuelog")
    db_alias = schema_editor.connection.alias
    pausas = Pausa.objects.all()
    acw_logs = Queuelog.objects.using(db_alias).filter(event__in=['PAUSEALL', 'PAUSE'], data1='0')
    acw_logs.update(data1='ACW')
    for pausa in pausas:
        nombre = pausa.nombre.upper()
        logs = Queuelog.objects.using(db_alias).filter(event__in=['PAUSEALL', 'PAUSE'],
                                                       data1=str(pausa.id))
        logs.update(data1=nombre)


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0140_auto_20180103_1445'),
    ]

    operations = [
        migrations.RunPython(cambiar_nombres_a_ids_de_pausas,
                             reverse_code=cambiar_ids_a_nombres_de_pausas),
    ]
