# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-12 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0142_auto_20180109_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacionmanual',
            name='calificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ominicontacto_app.Calificacion'),
        ),
    ]
