# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-24 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0143_auto_20180112_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='initial_boost_factor',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='queue',
            name='initial_predictive_model',
            field=models.BooleanField(default=False),
        ),
    ]
