# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-25 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0144_auto_20180124_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendacontacto',
            name='campana',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='agendas', to='ominicontacto_app.Campana'),
        ),
        migrations.AddField(
            model_name='agendamanual',
            name='campana',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='agendas_manuales', to='ominicontacto_app.Campana'),
        ),
    ]
