# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-30 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0146_auto_20180124_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campana',
            name='calificacion_campana',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='calificacioncampana', to='ominicontacto_app.CalificacionCampana'),
        ),
    ]
