# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-23 21:38
from __future__ import unicode_literals

from django.db import migrations


def adicionar_tipo_campana_queuelog(apps, schema_editor):
    """
    Adiciona información sobre el tipo de campaña en las entradas del modelo
    Queuelog
    """
    Queuelog = apps.get_model("ominicontacto_app", "queuelog")
    Campana = apps.get_model("ominicontacto_app", "campana")

    # copiamos la info del tipo de campaña en las entradas del modelo Queuelog
    for campana in Campana.objects_default.all():
        Queuelog.objects.filter(campana_id=campana.pk).update(data5=campana.type)


def rollback(apps, schema_editor):
    """
    Vuelve hacia la atrás los cambios de la migración de datos especificada en la función
    'adicionar_tipo_campana_queuelog'
    """
    Queuelog = apps.get_model("ominicontacto_app", "queuelog")
    qs_queuelog_modificados = Queuelog.objects.filter(
        campana_id__isnull=False).exclude(campana_id=-1)
    qs_queuelog_modificados.update(data5='')


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0146_auto_20180124_1454'),
    ]

    operations = [
        migrations.RunPython(adicionar_tipo_campana_queuelog, rollback),
    ]
