# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-17 14:40
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F


def update_sip_extension_in_agenteprofile(apps, schema_editor):
    """
    Actualiza el sip_extension en agenteprofile
    """

    AgenteProfile = apps.get_model("ominicontacto_app", "agenteprofile")

    # Actualiza el sip_extension con un valor lo suficientemente alto
    AgenteProfile.objects.all().update(sip_extension=F('user') + 10000)

    # Actualiza el sip_extension con en el real
    AgenteProfile.objects.all().update(sip_extension=F('user') + 1000)


def update_sip_extension_in_supervisorprofile(apps, schema_editor):
    """
    Actualiza el sip_extension en supervisorprofile
    """

    SupervisorProfile = apps.get_model("ominicontacto_app", "supervisorprofile")

    # Actualiza el sip_extension con un valor lo suficientemente alto
    SupervisorProfile.objects.all().update(sip_extension=F('user') + 10000)

    # Actualiza el sip_extension con en el real
    SupervisorProfile.objects.all().update(sip_extension=F('user') + 1000)


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0148_update_username_subscriber'),
    ]

    operations = [
        migrations.RunPython(update_sip_extension_in_agenteprofile),
        migrations.RunPython(update_sip_extension_in_supervisorprofile),
    ]
