# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-17 14:40
from __future__ import unicode_literals

from django.db import migrations


def update_sip_agente_grabacion(apps, schema_editor):
    """
    Actualiza el sip_extension en agenteprofile
    """

    Grabacion = apps.get_model("ominicontacto_app", "grabacion")
    AgenteProfile = apps.get_model("ominicontacto_app", "agenteprofile")

    # primero vamos actualizar las grabaciones que su sip agente no corresponde a ningún agente
    Grabacion.objects_default.exclude(
        sip_agente__in=AgenteProfile.objects.all().values_list('sip_extension', flat=True)).update(sip_agente=0)

    # ahora actualizamos la grabaciones realizando la busqueda por agente
    for agente in AgenteProfile.objects.all():
        Grabacion.objects_default.filter(sip_agente=agente.sip_extension).update(sip_agente=agente.user.id + 1000)


def rollback(apps, schema_editor):
    """
    Esta migración es para el reverse_code
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0148_update_username_subscriber'),
    ]

    operations = [
        migrations.RunPython(update_sip_agente_grabacion, reverse_code=rollback),
    ]
