# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-16 19:00
from __future__ import unicode_literals

from django.db import migrations

ESTADO_EN_DEFINICION = 1
ESTADO_TEMPLATE_EN_DEFINICION = 7


def eliminar_campanas_estados_intermedios(apps, schema_editor):
    """
    Elimina todas las campañas con estados intermedios previo a la eliminación de esos campos
    en el modelo Campana pues representan campañas que no habrían sido terminadas de completar
    de acuerdo al esquema anterior de wizards
    """
    Campana = apps.get_model("ominicontacto_app", "campana")

    Campana.objects_default.filter(
        estado__in=[ESTADO_EN_DEFINICION, ESTADO_TEMPLATE_EN_DEFINICION]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0149_grupos_calificaciones_a_opciones_calificaciones'),
    ]

    operations = [
        migrations.RunPython(eliminar_campanas_estados_intermedios, migrations.RunPython.noop),
    ]
