# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-06 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0149_permite_nulidad_calificacion_campana'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcionCalificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Gesti\xf3n')], default=0)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='opcioncalificacion',
            name='campana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='opciones_calificacion',
                                    to='ominicontacto_app.Campana'),
        ),
    ]
