# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-31 16:10
from __future__ import unicode_literals

from django.db import migrations


def restaurar_grupos_calificaciones_campanas(apps, schema_editor):
    """
    Crea un grupo de calificaciones con las existentes asociadas a una campaña y lo asocia a
    dicha campaña mediante el modelo CalificacionCampana
    """

    Campana = apps.get_model("ominicontacto_app", "campana")
    CalificacionCampana = apps.get_model('ominicontacto_app', 'calificacioncampana')

    for campana in Campana.objects_default.all():
        grupo_calificacion_campana = CalificacionCampana.objects.create(nombre=campana.nombre)
        grupo_calificacion_campana.calificacion.add(*campana.calificaciones_campana.all())
        campana.calificacion_campana = grupo_calificacion_campana
        campana.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0149_auto_20180130_1854'),
    ]

    operations = [
        migrations.RunPython(code=migrations.RunPython.noop,
                             reverse_code=restaurar_grupos_calificaciones_campanas)
    ]
