# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-30 21:54
from __future__ import unicode_literals

from django.db import migrations


def adicionar_calificaciones_campana(apps, schema_editor):
    """
    Adiciona las opciones de calificación a una campaña de acuerdo
    a partir de las calificaciones en el grupo de calificacion asociado
    a la campaña
    """
    Campana = apps.get_model("ominicontacto_app", "campana")
    OpcionCalificacion = apps.get_model('ominicontacto_app', 'opcioncalificacion')
    Calificacion = apps.get_model('ominicontacto_app', 'calificacion')

    GESTION = 1

    for campana in Campana.objects_default.all():
        # creamos las opciones de calificacion que relacionan las campañas con las calificaciones
        # todas tendrán inicialmente el valor de opción por defecto NO_ACCION, excepto la
        # calificación que corresponde con el tipo de gestión de la campaña
        opciones_clasificacion = [
            OpcionCalificacion(campana=campana, calificacion=calificacion)
            for calificacion in campana.calificacion_campana.calificacion.all()
            if calificacion.nombre != campana.gestion]
        calificacion_gestion, _ = Calificacion.objects.get_or_create(nombre=campana.gestion)
        opciones_clasificacion.append(OpcionCalificacion(
            campana=campana, calificacion=calificacion_gestion, tipo=GESTION))
        OpcionCalificacion.objects.bulk_create(opciones_clasificacion)


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0149_modelo_intermedio_campanas_calificaciones'),
    ]

    operations = [
        migrations.RunPython(code=adicionar_calificaciones_campana,
                             reverse_code=migrations.RunPython.noop),
    ]
