# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-09 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0150_elimina_estados_obsoletos_campanas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campana',
            name='estado',
            field=models.PositiveIntegerField(choices=[(2, 'Activa'), (3, 'Finalizada'),
                                                       (4, 'Borrada'), (5, 'Pausada'),
                                                       (6, 'Inactiva'), (8, 'Template Activo'),
                                                       (9, 'Template Borrado')], default=6),
        ),
    ]
