# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-31 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0150_auto_20180131_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacioncampana',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='campana',
            name='calificacion_campana',
        ),
        migrations.DeleteModel(
            name='CalificacionCampana',
        ),
    ]
