# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-19 15:22
from __future__ import unicode_literals

from django.db import migrations


def update_interface_in_queue_member_table(apps, schema_editor):
    """
    Actualiza la interface en queue_member_table
    """

    QueueMember = apps.get_model("ominicontacto_app", "queuemember")

    for queue_member in QueueMember.objects_default.all():
        sip_extension = queue_member.member.sip_extension
        interface = """Local/{0}@from-queue/n""".format(sip_extension)
        queue_member.interface = interface
        queue_member.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0150_update_sip_extension_agenteprofile_supervisorprofile'),
    ]

    operations = [
        migrations.RunPython(update_interface_in_queue_member_table),
    ]
