# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-20 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0151_update_interface_queue_member_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroExtraParaWebform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(max_length=32)),
                ('columna', models.CharField(max_length=32)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_extra_para_webform', to='ominicontacto_app.Campana')),
            ],
        ),
    ]
