# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-21 12:20
from __future__ import unicode_literals

from django.db import migrations
from django.db import connection


def crea_tabla_cdr(apps, schema_editor):
    """
    Actualiza la tabla subscriber con un valor lo suficientemente alto
    para que no coincida con ningun valor de id de usuario
    """

    cursor = connection.cursor()
    sql = """CREATE TABLE cdr (
        calldate timestamp  ,
        clid varchar (80)  ,
        src varchar (80)  ,
        dst varchar (80)  ,
        dcontext varchar (80)  ,
        channel varchar (80)  ,
        dstchannel varchar (80)  ,
        lastapp varchar (80)  ,
        lastdata varchar (80)  ,
        duration int  ,
        billsec int  ,
        disposition varchar (45)  ,
        amaflags int  ,
        accountcode varchar (20)  ,
        uniqueid varchar (150)  ,
        userfield varchar (255)  ,
        oml1 varchar (80)  ,
        oml2 varchar (80)  ,
        oml3 varchar (80)  ,
        oml4 varchar (80)
        )"""

    cursor.execute(sql)


def rollback(apps, schema_editor):
    """
    Esta migración es para el reverse_code
    """
    cursor = connection.cursor()
    sql = """drop table cdr"""

    cursor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0151_update_interface_queue_member_table'),
    ]

    operations = [
        migrations.RunPython(crea_tabla_cdr, reverse_code=rollback),

    ]
