# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-05 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0153_parametroextraparawebform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacioncliente',
            name='wombat_id',
            field=models.IntegerField(default=0),
        ),
    ]
