# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-13 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0154_auto_20180307_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
    ]
