# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-02 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0154_auto_20180305_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacioncliente',
            name='wombat_id',
        ),
        migrations.AlterField(
            model_name='wombatlog',
            name='calificacion',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='wombatlog',
            name='metadata',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='wombatlog',
            name='telefono',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='wombatlog',
            name='timeout',
            field=models.IntegerField(default=0),
        ),
    ]
