# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-04 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0155_remove_user_is_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='grabacion',
            name='duracion',
            field=models.IntegerField(default=0),
        ),
    ]
