# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-10 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0156_grabacion_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='borrado',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
