# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-13 12:37
from __future__ import unicode_literals

from django.db import migrations
import json


def agregar_bd_contacto_vacias(apps, schema_editor):
    """
    Se crea una base de datos vacía con campos TELEFONO, NOMBRE y APELLIDO para todas las Campañas
    que no tengan
    """
    BaseDatosContacto = apps.get_model("ominicontacto_app", "BaseDatosContacto")
    Campana = apps.get_model("ominicontacto_app", "Campana")

    campanas_sin_bd = Campana.objects_default.filter(bd_contacto__isnull=True).exclude(
        estado__in=[1, 7, 8, 9])
    for campana in campanas_sin_bd:
        metadata = {
            "prim_fila_enc": False,
            "cant_col": 3,
            "nombres_de_columnas": ["telefono", "nombre", "apellido"],
            "cols_telefono": [0]
        }
        params = {
            'nombre': 'BD-AUTO-%d-%s' % (campana.id, campana.nombre),
            'archivo_importacion': '-',
            'nombre_archivo_importacion': '-',
            'metadata': json.dumps(metadata),
            'sin_definir': False,
            'estado': 1,
        }
        base = BaseDatosContacto.objects.create(**params)
        campana.bd_contacto = base
        campana.save()


def rollback(apps, schema_editor):
    """
    Imposible saber con certeza cuales son las campañas que no tenían base de datos
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0163_elimina_estados_obsoletos_campanas_modelo'),
    ]

    operations = [
        migrations.RunPython(agregar_bd_contacto_vacias, rollback),
    ]
