# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-16 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0164_asignar_bd_contacto_vacias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calificacionmanual',
            old_name='es_gestion',
            new_name='es_venta',
        ),
        migrations.AddField(
            model_name='calificacionmanual',
            name='contacto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='ominicontacto_app.Contacto'),
        ),
        migrations.AddField(
            model_name='calificacionmanual',
            name='wombat_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='calificacionmanual',
            name='telefono',
            field=models.CharField(max_length=128, blank=True, null=True),
        ),
    ]
