# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-16 13:43
from __future__ import unicode_literals

from django.db import migrations


def crear_contacto_y_metadata(apps, schema_editor):
    """
    Usar el campo telefono para crear un nuevo contacto.
    Usar el campo Metadata para crear un MetadataCliente
    """
    CalificacionManual = apps.get_model('ominicontacto_app', 'calificacionmanual')
    Contacto = apps.get_model('ominicontacto_app', 'Contacto')
    MetadataCliente = apps.get_model('ominicontacto_app', 'MetadataCliente')

    calificaciones = CalificacionManual.objects.all()
    for calificacion in calificaciones:
        # Creo un nuevo contacto con el telefono de la Calificacion
        telefono = calificacion.telefono
        bd_contacto = calificacion.opcion_calificacion.campana.bd_contacto
        contacto = Contacto(telefono=telefono, datos='[]', bd_contacto=bd_contacto)
        contacto.save()
        calificacion.contacto = contacto
        calificacion.save()

        # Creo un Metadata cliente con el campo metadata.
        if calificacion.es_venta and calificacion.metadata:
            MetadataCliente.objects.create(agente=calificacion.agente,
                                           campana=calificacion.opcion_calificacion.campana,
                                           contacto=contacto,
                                           metadata=calificacion.metadata)


def rollback(apps, schema_editor):
    """
    Borrar el Metadata y el Contacto asociado a la CalificacionManual
    """
    CalificacionManual = apps.get_model('ominicontacto_app', 'calificacionmanual')
    MetadataCliente = apps.get_model('ominicontacto_app', 'MetadataCliente')

    calificaciones = CalificacionManual.objects.all()
    for calificacion in calificaciones:
        # Elimino el objeto Metadata asociado, pasando su metadata a la calificacion.
        metadata = MetadataCliente.objects.filter(contacto=calificacion.contacto)
        if metadata.count() > 0:
            calificacion.metadata = metadata[0].metadata
            metadata.delete()
        contacto = calificacion.contacto
        calificacion.contacto = None
        calificacion.telefono = contacto.telefono
        calificacion.save()
        # Elimino el contacto pasando su telefono a la calificacion.
        contacto.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0165_igualar_calmanual_a_calcliente'),
    ]

    operations = [
        migrations.RunPython(crear_contacto_y_metadata, reverse_code=rollback),
    ]
