# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-06 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0170_elimina_modelo_calificacion_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamanual',
            name='agente',
        ),
        migrations.RemoveField(
            model_name='agendamanual',
            name='campana',
        ),
        migrations.DeleteModel(
            name='AgendaManual',
        ),
    ]
