# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-23 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0171_auto_20180406_1656'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Queuelog',
        ),
    ]
