# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-05-07 20:48
from __future__ import unicode_literals

from django.db import migrations, models


def update_queue_asterisk(apps, schema_editor):

    queue_table = apps.get_model("ominicontacto_app", "Queue")
    queue_table.objects_default.all().update(queue_asterisk=models.F("campana"))


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0172_delete_queuelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='queue_asterisk',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(update_queue_asterisk,
                             reverse_code=update_queue_asterisk),

    ]
