# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-27 14:53
from __future__ import unicode_literals

from django.db import migrations, connection
from django.db.models import F


def remove_field(apps, schema_editor):
    """
    Esta migración remueve la columna queue_asterisk
    """
    cursor = connection.cursor()
    sql = """ALTER TABLE queue_table DROP COLUMN queue_asterisk"""

    cursor.execute(sql)


def rollback(apps, schema_editor):
    """
    Esta migración es para el reverse_code
    """

    # primer paso crear columna queue asterisk
    cursor = connection.cursor()
    sql = """ALTER TABLE queue_table  ADD COLUMN queue_asterisk integer"""
    cursor.execute(sql)
    # segundo paso asignar valores por default
    queue_table = apps.get_model("ominicontacto_app", "Queue")
    queue_table.objects_default.all().update(queue_asterisk=F("campana"))
    # tercer paso setear como not null
    cursor = connection.cursor()
    sql = """ALTER TABLE queue_table ALTER COLUMN queue_asterisk SET NOT NULL"""
    cursor.execute(sql)
    # cuarto paso agrega constraint de entero positivos
    cursor = connection.cursor()
    sql = """ALTER TABLE queue_table ADD CONSTRAINT queue_table_queue_asterisk_check CHECK (queue_asterisk >= 0)"""
    cursor.execute(sql)
    # quinto paso agrega constraint de unique
    cursor = connection.cursor()
    sql = """ALTER TABLE queue_table ADD CONSTRAINT queue_table_queue_asterisk_key UNIQUE (queue_asterisk)"""
    cursor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0172_delete_queuelog'),
    ]

    operations = [
        migrations.RunPython(remove_field, reverse_code=rollback),

    ]
