# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-27 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0172_delete_queuelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='queue_asterisk',
        ),
    ]
