# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-05-07 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0173_auto_20180507_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='queue_asterisk',
        ),
    ]
