# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-05-08 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0174_remove_queue_queue_asterisk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campana',
            name='type',
            field=models.PositiveIntegerField(choices=[(3, 'Entrante'), (2, 'Dialer'), (1, 'Manual'), (4, 'Preview')]),
        ),
        migrations.AlterField(
            model_name='duraciondellamada',
            name='tipo_llamada',
            field=models.PositiveIntegerField(choices=[(4, 'PREVIEW'), (2, 'DIALER'), (3, 'INBOUND'), (1, 'MANUAL')]),
        ),
        migrations.AlterField(
            model_name='grabacion',
            name='tipo_llamada',
            field=models.PositiveIntegerField(choices=[(2, 'DIALER'), (3, 'INBOUND'), (1, 'MANUAL'), (4, 'PREVIEW')]),
        ),
    ]
