# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-05-28 13:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0175_auto_20180508_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCalificacionCliente',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True,
                                           verbose_name='ID')),
                ('es_venta', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(blank=True, editable=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('wombat_id', models.IntegerField(default=0)),
                ('agendado', models.BooleanField(default=False)),
                ('es_calificacion_manual', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'),
                                                           ('-', 'Deleted')], max_length=1)),
                ('agente', models.ForeignKey(
                    blank=True, db_constraint=False, null=True,
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    related_name='+', to='ominicontacto_app.AgenteProfile')),
                ('contacto', models.ForeignKey(
                    blank=True, db_constraint=False, null=True,
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    related_name='+', to='ominicontacto_app.Contacto')),
                ('history_user', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='+', to=settings.AUTH_USER_MODEL)),
                ('opcion_calificacion', models.ForeignKey(
                    blank=True, db_constraint=False,
                    null=True,
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    related_name='+', to='ominicontacto_app.OpcionCalificacion')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical calificacion cliente',
            },
        ),
    ]
