# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-05-31 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0176_historicalcalificacioncliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='audios',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='queues_anuncio_periodico', to='ominicontacto_app.ArchivoDeAudio'),
        ),
    ]
