# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-06-22 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0178_auto_20180619_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorprofile',
            name='timestamp',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
