# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-07-25 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0179_supervisorprofile_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='auto_pause',
            field=models.BooleanField(default=True),
        ),
    ]
