#! /bin/sh
#
# ominicontacto-daemon
#
# chkconfig: - 95 9
# description:  Daemon WEB de Omnileads

# Source function library.
. /lib/lsb/init-functions

RETVAL=0
USER=omnileads
GROUP=omnileads
CMD=/opt/omnileads/virtualenv/bin/uwsgi

export PYTHONPATH=/opt/omnileads/ominicontacto

. /opt/omnileads/virtualenv/bin/activate

# See how we were called.
case "$1" in
  start)
        echo -n "Starting OminicontactoDaemon... "
        # $CMD --ini /opt/omnileads/ominicontacto/oml_uwsgi.ini
        su -l -s /bin/bash -c "$CMD --ini /opt/omnileads/ominicontacto/oml_uwsgi.ini" $USER
        RETVAL=$?
        if [ $RETVAL -eq 0 ]
        then
                log_success_msg
        else
                log_failure_msg
        fi
        echo
        ;;
  stop)
        echo -n "Stopping OminicontactoDaemon... "
        pgrep -u omnileads uwsgi > /dev/null || {
                echo "OminicontactoDaemon no esta corriendo..."
                log_failure_msg
                exit 1
        }

        su -l -s /bin/bash -c "echo 'q' > /opt/omnileads/ominicontacto/.uwsgi-fifo" $USER
        RETVAL=$?
        if [ $RETVAL -eq 0 ]
        then
                log_success_msg
        else
                log_failure_msg
        fi
        echo
        ;;
  reload)
        echo -n "Reload de OminicontactoDaemon... "
        pgrep -u omnileads uwsgi > /dev/null || {
            log_failure_msg
			echo "OminicontactoDaemon no esta corriendo..."
            exit 1
        }

        su -l -s /bin/bash -c "echo 'r' > /opt/omnileads/ominicontacto/.uwsgi-fifo" $USER
        RETVAL=$?
        if [ $RETVAL -eq 0 ]
        then
                log_success_msg 
        else
                log_failure_msg
        fi
        echo
        ;;
  status)
        pgrep -u omnileads uwsgi > /dev/null || {
                log_failure_msg
                echo "OminicontactoDaemon no esta corriendo..."
                exit 1
        }
        log_success_msg
        echo "OminicontactoDaemon esta corriendo..."
        exit 0
        ;;
   *)
        echo "Usage: $0 start|stop|reload"
        exit 1
esac

exit $RETVAL
