#! /bin/sh
#
# ominicontacto-daemon
#
# chkconfig: - 95 9
# description:  Daemon WEB de Omnileads

# Source function library.
. /lib/lsb/init-functions

RETVAL=0
USER=freetech
GROUP=freetech
CMD=/home/freetech/virtualenv/bin/uwsgi

export PYTHONPATH=/home/freetech/ominicontacto

. /home/freetech/virtualenv/bin/activate

# See how we were called.
case "$1" in
  start)
        echo -n "Starting OminicontactoDaemon... "
        # $CMD --ini /home/freetech/ominicontacto/oml_uwsgi.ini
        su -l -s /bin/bash -c "$CMD --ini /home/freetech/ominicontacto/oml_uwsgi.ini" $USER
        RETVAL=$?
        if [ $RETVAL -eq 0 ]
        then
                log_success_msg
        else
                log_failure_msg
        fi
        echo
        ;;
  stop)
        echo -n "Stopping OminicontactoDaemon... "
        #pgrep -u freetech uwsgi > /dev/null || {
        fuser -k -n tcp 8000 > /dev/null || {
		echo "OminicontactoDaemon no esta corriendo..."
                log_failure_msg
                exit 1
        }

        su -l -s /bin/bash -c "echo 'q' > /home/freetech/ominicontacto/.uwsgi-fifo" $USER
        RETVAL=$?
        if [ $RETVAL -eq 0 ]
        then
                log_success_msg
        else
                log_failure_msg
        fi
        echo
        ;;
  reload)
        echo -n "Reload de OminicontactoDaemon... "
        pgrep -u freetech uwsgi > /dev/null || {
            log_failure_msg
			echo "OminicontactoDaemon no esta corriendo..."
            exit 1
        }

        su -l -s /bin/bash -c "echo 'r' > /home/freetech/ominicontacto/.uwsgi-fifo" $USER
        RETVAL=$?
        if [ $RETVAL -eq 0 ]
        then
                log_success_msg 
        else
                log_failure_msg
        fi
        echo
        ;;
  status)
        pgrep -u freetech uwsgi > /dev/null || {
                log_failure_msg
                echo "OminicontactoDaemon no esta corriendo..."
                exit 1
        }
        log_success_msg
        echo "OminicontactoDaemon esta corriendo..."
        exit 0
        ;;
   *)
        echo "Usage: $0 start|stop|reload"
        exit 1
esac

exit $RETVAL
