Vagrant.configure("2") do |config|
  config.vm.define "debian" do |nodo1|
# Tamaño del sisco principal, recordar antes instalar plugin vagrant-disksize
# No funciona con debian9, esta el issue levantado el github de plugin:
# https://github.com/sprotheroe/vagrant-disksize/issues
    #config.disksize.size = "20GB"
    nodo1.vm.box = "generic/debian9"
    nodo1.vm.box_version = "1.9.34"
    nodo1.vm.hostname = "debian-example"
    nodo1.vm.network "public_network", bridge: "enp2s0", ip: "192.168.99.61",     use_dhcp_assigned_default_route: true
    nodo1.vm.provision "shell",  inline: "
      sudo /bin/sh -c '
                      VAR=`cat /vagrant/id_rsa.pub`;
                      mkdir /root/.ssh/; touch /root/.ssh/authorized_keys;
                      echo $VAR >> /root/.ssh/authorized_keys;
                      sudo apt-get update -y;
                      DEBIAN_FRONTEND=noninteractive apt-get upgrade -y;
                      sudo apt-get install linux-image-amd64 -y
                      '"
    nodo1.vm.provider "virtualbox" do |vb|
      vb.name = "Debian-Staging"
      vb.memory = "2048"
      vb.cpus = "2"
    end
    nodo1.vm.synced_folder ".", "/vagrant", type: "rsync"
  end
  config.vm.define "ubuntu" do |nodo2|
  #  config.disksize.size = "20GB"
    nodo2.vm.box = "aspyatkin/ubuntu-18.04-server"
    nodo2.vm.box_version = "1.2.0"
    nodo2.vm.hostname = "ubuntu-example"
    nodo2.vm.network "public_network", bridge: "enp2s0", ip: "192.168.99.60", use_dhcp_assigned_default_route: true
    nodo2.vm.provision "shell",  inline: "
      sudo /bin/sh -c '
                      VAR=`cat /vagrant/id_rsa.pub`;
                      mkdir /root/.ssh/;
                      touch /root/.ssh/authorized_keys;
                      echo $VAR >> /root/.ssh/authorized_keys';
                      apt-get install python-minimal git -y;
                      sudo apt-get update -y;
                      sudo DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
                      '"
    nodo2.vm.provider "virtualbox" do |vb|
      vb.name = "Ubuntu-Staging"
      vb.memory = "2048"
      vb.cpus = "2"
    end
    nodo2.vm.synced_folder ".", "/vagrant", type: "rsync"
  end
  config.vm.define "centos" do |nodo3|
  #  config.disksize.size = "20GB"
    nodo3.vm.box = "centos/7"
    nodo3.vm.box_version = "1905.1"
    nodo3.vm.hostname = "centos-example.com"
    nodo3.vm.network "public_network", bridge: "enp2s0", ip: "192.168.99.62",     use_dhcp_assigned_default_route: true
    nodo3.vm.provision "shell",  inline: "
      sudo /bin/sh -c '
                      VAR=`cat /vagrant/id_rsa.pub`;
                      mkdir /root/.ssh/;
                      touch /root/.ssh/authorized_keys;
                      echo $VAR >> /root/.ssh/authorized_keys;
                      sudo yum install kernel-devel -y;
                      sudo yum update -y
                      '"
    nodo3.vm.provider "virtualbox" do |vb|
      vb.name = "Centos-Staging"
      vb.memory = "2048"
      vb.cpus = "2"
    end
    nodo3.vm.synced_folder ".", "/vagrant", type: "rsync"
  end
end
