Vagrant.configure("2") do |config|
  config.vm.define "centos" do |nodo1|
  #  config.disksize.size = "20GB"
    nodo1.vm.box = "centos/7"
    nodo1.vm.box_version = "1905.1"
    nodo1.vm.hostname = "centos-example.com"
    nodo1.vm.network "public_network", bridge: "enp2s0", ip: "172.16.20.62",     use_dhcp_assigned_default_route: true
    nodo1.vm.provision "shell",  inline: "
      sudo /bin/sh -c '
                      VAR=`cat /vagrant/id_rsa.pub`;
                      mkdir /root/.ssh/;
                      touch /root/.ssh/authorized_keys;
                      echo $VAR >> /root/.ssh/authorized_keys;
                      sudo yum update -y;
                      systemctl disable firewalld && systemctl stop firewalld;
                      sed -i \'s/^SELINUX=.*/SELINUX=disabled/\' /etc/sysconfig/selinux;
                      sed -i \'s/^SELINUX=.*/SELINUX=disabled/\' /etc/selinux/config
                      '"
    nodo1.vm.provider "virtualbox" do |vb|
      vb.name = "Centos-Staging"
      vb.memory = "2048"
      vb.cpus = "2"
    end
    nodo1.vm.synced_folder ".", "/vagrant", type: "rsync"
  end
end
