# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-08 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes_app', '0003_queue_log_insert_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llamadalog',
            name='archivo_grabacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
