# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-06-18 15:45
from __future__ import unicode_literals

from django.db import migrations, connection


SQL_ALTER_LONGITUD = """
ALTER TABLE queue_log ALTER COLUMN time TYPE character varying(100);
ALTER TABLE queue_log ALTER COLUMN callid TYPE character varying(100);
ALTER TABLE queue_log ALTER COLUMN queuename TYPE character varying(100);
ALTER TABLE queue_log ALTER COLUMN agent TYPE character varying(100);
ALTER TABLE queue_log ALTER COLUMN event TYPE character varying(100);
"""


def adicionar_longitud_campos_queue_log(apps, schema_editor):
    cursor = connection.cursor()
    cursor.execute(SQL_ALTER_LONGITUD)


class Migration(migrations.Migration):

    dependencies = [
        ('reportes_app', '0004_llamadalog_archivo_grabacion_length'),
    ]

    operations = [
        migrations.RunPython(
            adicionar_longitud_campos_queue_log, reverse_code=migrations.RunPython.noop)
    ]
