# Generated by Django 2.2.7 on 2023-10-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes_app', '0008_transferenciaaencuestalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadagentelog',
            name='time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
