# Generated by Django 3.2.19 on 2024-04-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes_app', '0010_update_queue_log_insert_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisSentimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('callid', models.CharField(max_length=32, unique=True)),
                ('result', models.CharField(blank=True, max_length=32, null=True)),
                ('url_audio', models.TextField(blank=True, null=True)),
                ('url_transcription', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
