# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
# Playbook de instalacion de Omnileads
# Utilza como variables de entorno el archivo group_vars/all y el archivo de inventario hosts
# Utiliza como archivo de configuracion /var/tmp/ansible/ansible.cfg
# Cositas a tener en cuenta:
# https://docs.ansible.com/ansible/2.9/user_guide/playbooks_conditionals.html
# https://docs.ansible.com/ansible/2.9/user_guide/playbooks_loops.html
# https://docs.ansible.com/ansible/2.9/intro_configuration.html
---

# hosts: le decimos que seccion del hosts se va  usar: [prodenv-container]
- name: Omnileads-Docker integration
  hosts: docker
  roles:
    - { role: docker, tags: docker_deploy }

# hosts: le decimos que seccion del hosts se va  usar: [prodenv-aio]
- name: OMniLeads AIO installation
  hosts: prodenv-aio

# el gather_facts es para obtener valores de variables predeterminadas de ansible, la mas usada es ansible_os_family.
# Esta variable te dice que familia de OS es el servidor a deployar
  gather_facts: True

# Aca comienza la ejecucion de tasks. Las tasks se agrupan en roles, los roles se agrupan dependiendo del componente del sistema
# https://docs.ansible.com/ansible/2.5/user_guide/playbooks_reuse_roles.html
  roles:
          - prerequisitos
          - { role: database, tags: database }
          - {role: oml_server, tags: omniapp }
          - { role: asterisk, tags: asterisk }
          - {role: kamailio, tags: kamailio }
          - {role: omniapp_second, tags: omiapp }
          - { role: dialer, tags: dialer }
