#!/bin/bash
PGUSER=$POSTGRES_USER psql -c  "CREATE EXTENSION plpythonu"
PGUSER=$POSTGRES_USER psql -c "GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;"
PGUSER=$POSTGRES_USER psql -c "ALTER USER $POSTGRES_USER WITH SUPERUSER;"
