#!/bin/bash
PGUSER=$POSTGRES_USER psql -d $POSTGRES_DB -c  "CREATE EXTENSION plperl"
PGUSER=$POSTGRES_USER psql -d template1 -c  "CREATE EXTENSION plpeRL"
PGUSER=$POSTGRES_USER psql -c "GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;"
PGUSER=$POSTGRES_USER psql -c "ALTER USER $POSTGRES_USER WITH SUPERUSER;"
