# Generated by Django 2.2.7 on 2022-12-30 23:25

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion_telefonia_app', '0018_regex_did_entrante_patron_de_discado_saliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionProveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_proveedor', models.IntegerField(choices=[(0, 'Twilio'), (1, 'Meta'), (2, 'GupShup')])),
                ('configuracion', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='configuracionproveedor_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='configuracionproveedor_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=100)),
                ('configuracion', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='linea_created', to=settings.AUTH_USER_MODEL)),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='configuracion_telefonia_app.DestinoEntrante')),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='configuracion_telefonia_app.GrupoHorario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateWhatsapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('identificador', models.CharField(max_length=100)),
                ('texto', models.TextField(blank=True, null=True)),
                ('idioma', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('creado', models.CharField(max_length=100)),
                ('modificado', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates_whatsapp', to='whatsapp_app.Linea')),
            ],
        ),
        migrations.CreateModel(
            name='PlantillaMensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.IntegerField(choices=[(0, 'Texto'), (1, 'Imagen')])),
                ('configuracion', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='plantillamensaje_created', to=settings.AUTH_USER_MODEL)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_mensaje', to='whatsapp_app.Linea')),
                ('updated_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='plantillamensaje_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='linea',
            name='mensaje_bienvenida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linea_mensaje_bienvenida', to='whatsapp_app.PlantillaMensaje'),
        ),
        migrations.AddField(
            model_name='linea',
            name='mensaje_despedida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linea_mensaje_despedida', to='whatsapp_app.PlantillaMensaje'),
        ),
        migrations.AddField(
            model_name='linea',
            name='mensaje_fueradehora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linea_mensaje_fueradehora', to='whatsapp_app.PlantillaMensaje'),
        ),
        migrations.AddField(
            model_name='linea',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='whatsapp_app.ConfiguracionProveedor'),
        ),
        migrations.AddField(
            model_name='linea',
            name='updated_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='linea_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GrupoTemplateWhatsapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('nombre', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='grupotemplatewhatsapp_created', to=settings.AUTH_USER_MODEL)),
                ('templates', models.ManyToManyField(to='whatsapp_app.TemplateWhatsapp')),
                ('updated_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='grupotemplatewhatsapp_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrupoPlantillaMensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('nombre', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='grupoplantillamensaje_created', to=settings.AUTH_USER_MODEL)),
                ('plantillas', models.ManyToManyField(to='whatsapp_app.TemplateWhatsapp')),
                ('updated_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='grupoplantillamensaje_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='templatewhatsapp',
            constraint=models.UniqueConstraint(fields=('linea_id', 'identificador'), name='identificador_unico'),
        ),
    ]
