# Generated by Django 2.2.7 on 2023-01-10 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantillamensaje',
            name='linea',
        ),
    ]
