# Generated by Django 3.2.19 on 2024-02-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0002_alter_configuracionwhatsappcampana_grupo_plantilla_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacionwhatsapp',
            name='client_alias',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
