# Generated by Django 2.2.7 on 2023-09-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0004_conversacionwhatsapp_mensajewhatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacionwhatsapp',
            name='timestamp',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
