# Generated by Django 3.2.19 on 2024-02-26 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0004_alter_mensajewhatsapp_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacionwhatsapp',
            name='conversation_disposition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='ominicontacto_app.historicalcalificacioncliente'),
        ),
    ]
