# Generated by Django 2.2.7 on 2023-10-02 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0005_conversacionwhatsapp_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversacionwhatsapp',
            name='expire',
        ),
        migrations.RemoveField(
            model_name='conversacionwhatsapp',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='mensajewhatsapp',
            name='timestamp',
        ),
    ]
