# Generated by Django 3.2.19 on 2024-03-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0005_conversacionwhatsapp_conversation_disposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacionwhatsapp',
            name='error_ex',
            field=models.JSONField(default=dict),
        ),
    ]
