# Generated by Django 3.2.19 on 2024-04-12 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0006_conversacionwhatsapp_error_ex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversacionwhatsapp',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mensajewhatsapp',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
