# Generated by Django 2.2.7 on 2023-10-02 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0006_auto_20231002_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacionwhatsapp',
            name='expire',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='conversacionwhatsapp',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mensajewhatsapp',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
