# Generated by Django 2.2.7 on 2023-10-16 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0007_auto_20231002_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversacionwhatsapp',
            name='conversation_id',
        ),
        migrations.AddField(
            model_name='conversacionwhatsapp',
            name='is_disposition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mensajewhatsapp',
            name='message_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensajewhatsapp',
            name='status',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conversacionwhatsapp',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mensajewhatsapp',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='whatsapp_app.ConversacionWhatsapp'),
        ),
    ]
