# Generated by Django 3.2.19 on 2024-08-01 09:54

from django.db import migrations, models
import whatsapp_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0007_auto_20240412_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajewhatsapp',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=whatsapp_app.models.upload_to),
        ),
        migrations.AddField(
            model_name='templatewhatsapp',
            name='identificador_media',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='templatewhatsapp',
            name='link_media',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
