# Generated by Django 3.2.19 on 2024-08-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0008_add_mensajewhatsapp_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajewhatsapp',
            name='fail_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
