# Generated by Django 2.2.7 on 2023-11-02 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0008_auto_20231016_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionwhatsappcampana',
            name='grupo_template_whatsapp',
        ),
        migrations.RemoveField(
            model_name='conversacionwhatsapp',
            name='conversation_type',
        ),
        migrations.AddField(
            model_name='templatewhatsapp',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='conversacionwhatsapp',
            name='campana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='ominicontacto_app.Campana'),
        ),
        migrations.AlterField(
            model_name='conversacionwhatsapp',
            name='expire',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mensajewhatsapp',
            name='conversation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='whatsapp_app.ConversacionWhatsapp'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GrupoTemplateWhatsapp',
        ),
    ]
