# Generated by Django 3.2.19 on 2024-11-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0009_mensajewhatsapp_fail_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuinteractivowhatsapp',
            old_name='texto_opciones',
            new_name='menu_body',
        ),
        migrations.AddField(
            model_name='menuinteractivowhatsapp',
            name='menu_button',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuinteractivowhatsapp',
            name='menu_footer',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='menuinteractivowhatsapp',
            name='menu_header',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuinteractivowhatsapp',
            name='texto_opcion_incorrecta',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menuinteractivowhatsapp',
            name='timeout',
            field=models.IntegerField(null=True),
        ),
    ]
