# Generated by Django 2.2.7 on 2023-11-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0009_auto_20231102_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacionwhatsapp',
            name='atendida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversacionwhatsapp',
            name='error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversacionwhatsapp',
            name='saliente',
            field=models.BooleanField(default=False),
        ),
    ]
