# Generated by Django 2.2.7 on 2023-11-20 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0010_auto_20231116_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacionwhatsapp',
            name='line',
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE,
                related_name='conversaciones', to='whatsapp_app.Linea'),
            preserve_default=False,
        ),
    ]
