# Generated by Django 3.2.19 on 2024-12-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0010_auto_20241119_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcionmenuinteractivowhatsapp',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
