# Generated by Django 2.2.7 on 2023-11-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0011_conversacionwhatsapp_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacionwhatsapp',
            name='date_last_interaction',
            field=models.DateTimeField(null=True),
        ),
    ]
