# Generated by Django 3.2.19 on 2025-01-31 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0011_alter_opcionmenuinteractivowhatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuinteractivowhatsapp',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuinteractivowhatsapp',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menuinteractivo', to='whatsapp_app.linea'),
        )
    ]
