# Generated by Django 2.2.7 on 2023-11-02 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_telefonia_app', '0019_tipo_destino_entrante_menuwhatsapp'),
        ('whatsapp_app', '0012_conversacionwhatsapp_date_last_interaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuInteractivoWhatsapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('texto_opciones', models.CharField(max_length=100)),
                ('texto_opcion_incorrecta', models.CharField(max_length=100)),
                ('texto_derivacion', models.CharField(max_length=100)),
                ('timeout', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OpcionMenuInteractivoWhatsapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('opcion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                related_name='opcion_menu_whatsapp',
                                                to='configuracion_telefonia_app.OpcionDestino')),
            ],
        ),
    ]
