# Generated by Django 2.2.7 on 2023-12-26 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0013_menuinteractivowhatsapp_opcionmenuinteractivowhatsapp'),
    ]
    operations = [
        migrations.AddField(
            model_name='conversacionwhatsapp',
            name='whatsapp_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
