# Generated by Django 3.2.19 on 2025-07-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0014_alter_line_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatewhatsapp',
            name='texto_header',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='templatewhatsapp',
            name='link_media',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
