# Generated by Django 3.2.19 on 2025-09-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0015_auto_20250721_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatewhatsapp',
            name='botones',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
