# Generated by Django 3.2.25 on 2026-03-26 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0016_templatewhatsapp_botones'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcionmenuinteractivowhatsapp',
            name='message_before_campaign',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                related_name='opciones_menu_pre_campana', to='whatsapp_app.plantillamensaje'),
        ),
        migrations.AddField(
            model_name='opcionmenuinteractivowhatsapp',
            name='send_message_before_campaign',
            field=models.BooleanField(default=False),
        ),
    ]
