FROM {{ dialer_image }}

ENV WD_VERSION {{ wombat_version }}
ENV JAVA_CONNECTOR_VERSION 2.3.0
RUN apk update \
    && apk add wget unzip \
    && cd /usr/local/tomcat/webapps/ \
    && wget http://downloads.loway.ch/wd/WombatDialer-${WD_VERSION}.tar.gz  \
    && tar xzvf WombatDialer-${WD_VERSION}.tar.gz \
    && mv wombatdialer-18.08.3 wombat \
    && sed -i -- 's/127.0.0.1/mariadb/g' wombat/WEB-INF/tpf.properties \
    && rm -rf  WombatDialer-${WD_VERSION}.tar.gz \
    && wget https://downloads.mariadb.com/Connectors/java/connector-java-2.3.0/mariadb-java-client-${JAVA_CONNECTOR_VERSION}.jar \
    && cp mariadb-java-client-${JAVA_CONNECTOR_VERSION}.jar wombat/WEB-INF/lib/ \
    && rm -rf mariadb-java-client-${JAVA_CONNECTOR_VERSION}.jar
