FROM {{ dialer_image }}

ENV WD_VERSION {{ wombat_version }}
ENV JAVA_CONNECTOR_VERSION 2.3.0
RUN apk update \
    && apk add wget unzip \
    && cd /usr/local/tomcat/webapps/ \
    && wget {{ wombat_repo }} \
    && tar xzvf WombatDialer-${WD_VERSION}.tar.gz \
    && mv wombatdialer-{{  wombat_version.split("-")[0] | lower }} wombat \
    && rm -rf  WombatDialer-${WD_VERSION}.tar.gz \
    && wget https://downloads.mariadb.com/Connectors/java/connector-java-2.3.0/mariadb-java-client-${JAVA_CONNECTOR_VERSION}.jar \
    && cp mariadb-java-client-${JAVA_CONNECTOR_VERSION}.jar wombat/WEB-INF/lib/ \
    && rm -rf mariadb-java-client-${JAVA_CONNECTOR_VERSION}.jar
