# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
---

# Se descarga la key para el repositorio de postgres
- name: Download postgresql-{{ postgresql_version }} key
  rpm_key: key="{{ postgresql_key }}" state=present validate_certs=no
  retries: 3
  delay: 3
  register: result
  until: result is success
  when: postgresql_new_installed.rc != 3 and ansible_distribution != "Amazon"

# Se instala el repo de postgresql
- name: Install of postgresql-{{ postgresql_version }} repository
  yum: name={{ postgresql_repo }} state=present validate_certs=no update_cache=yes
  become: yes
  become_method: sudo
  retries: 3
  delay: 3
  register: result
  until: result is success
  when: postgresql_new_installed.rc != 3 and ansible_distribution != "Amazon"

  #Se instalan todos los paquetes de postgresql
- name: Install of postgresql-{{ postgresql_version }} packages
  shell: "yum install postgresql{{ postgresql_version }}* --skip-broken -y"
  retries: 3
  delay: 3
  register: result
  until: result is success
  when: postgresql_new_installed.rc != 3 and ansible_distribution != "Amazon" and postgres_host is not defined

  #Se instala repositorio postgresql amazon linux
- name: Install of postgresql-{{ postgresql_version }} repository
  shell: "amazon-linux-extras enable postgresql11"
  when: postgresql_new_installed.rc != 3 and ansible_distribution == "Amazon"

  #Se instala postgresql amazon linux
- name: Install of postgresql-{{ postgresql_version }} packages
  yum: name={{ item }} state=present update_cache=yes
  with_items:
    - postgresql
    - postgresql-server
    - postgresql-devel
    - postgresql-odbc
    - postgresql-docs
    - postgresql-plperl
  retries: 3
  delay: 3
  register: result
  until: result is success
  when: postgresql_new_installed.rc != 3 and ansible_distribution == "Amazon" and postgres_host is not defined

# Se instala solo el postgresql client para cuando postgres es externo
- name: Install of postgresql client
  yum: name={{ item }} state=present
  with_items:
    - postgresql11
    - postgresql11-odbc
  when: postgres_host is defined and ansible_distribution != "Amazon"

# Se instala solo el postgresql client para cuando postgres es externo
- name: Install of postgresql client
  yum: name={{ item }} state=present
  with_items:
    - postgresql
    - postgresql-odbc
  when: postgres_host is defined and ansible_distribution == "Amazon"
