Vagrant.configure("2") do |config|
    config.env.enable
    config.vm.define "ubuntu" do |devenv|
      devenv.vm.box = "bento/ubuntu-20.04"
      devenv.vm.hostname = ENV['BOX_HOSTNAME']
      devenv.vm.network "public_network", bridge: ENV['BOX_NIC'], ip: ENV['BOX_IPV4'], use_dhcp_assigned_default_route: true
      devenv.vm.network "forwarded_port", guest: 443, host: 443
      devenv.vm.network "forwarded_port", guest: 8000, host: 8000
      devenv.vm.network "forwarded_port", guest: 6379, host: 6379
      devenv.vm.network "forwarded_port", guest: 6060, host: 6060, protocol: "udp"
      devenv.vm.network "forwarded_port", guest: 9001, host: 9001
      devenv.vm.provision "shell" do |s|
        # s.env   = { 'CICD_ROOT_PUBLIC_KEY' => ENV['CICD_ROOT_PUBLIC_KEY'],
        #             'omnileads_release' => ENV['omnileads_release'],
        #             'STAGE' => ENV['STAGE'],
        #             'NIC' => ENV['NIC'],
        #             'TZ' => ENV['TZ'],
        #             'ami_user' => ENV['ami_user'],
        #             'ami_password' => ENV['ami_password'],
        #             'dialer_user' => ENV['dialer_user'],
        #             'dialer_password' => ENV['dialer_password'],
        #             'pg_database' => ENV['pg_databasels'],
        #             'pg_username' => ENV['pg_username'],
        #             'pg_password' => ENV['pg_password'],
        #             'init_env' => ENV['init_env']
        #           }
        s.path  = "./deploy.sh"
      end
      devenv.vm.provider "virtualbox" do |vb|
        vb.name = "DevEnv"
        vb.memory = "2048"
        vb.cpus = "2"
      end
      devenv.vm.synced_folder ENV['PATH2BIND'], "/home/vagrant/"
  end
end
  