CREATE TABLE cdr ( 
        calldate timestamp  , 
        clid varchar (80)  , 
        src varchar (80)  , 
        dst varchar (80)  , 
        dcontext varchar (80)  , 
        channel varchar (80)  , 
        dstchannel varchar (80)  , 
        lastapp varchar (80)  , 
        lastdata varchar (80)  , 
        duration int  , 
        billsec int  , 
        disposition varchar (45)  , 
        amaflags int  , 
        accountcode varchar (20)  , 
        uniqueid varchar (150)  , 
        userfield varchar (255)  ,
		oml1 varchar (80)  ,
		oml2 varchar (80)  ,
		oml3 varchar (80)  ,
		oml4 varchar (80) 
);
