export const DESTINATION_FORM_TYPES = {
    CAMPAIGN: 1,
    INTERACTIVE: 13,
    CLOSING_MESSAGE: 12
};

export const DESTINATION_OPTION_TYPES = {
    CAMPAIGN: 1,
    INTERACTIVE: 13,
    CLOSING_MESSAGE: 12
};

export const DESTINATION_TYPES_BACK = {
    CAMPAIGN: 1,
    INTERACTIVE: 13,
    CLOSING_MESSAGE: 12
};
