Vagrant.configure("2") do |config|
  config.vm.define "centos" do |nodo1|
#    config.disksize.size = "20GB"
    nodo1.vm.box = "centos/7"
    nodo1.vm.box_version = "1905.1"
    nodo1.vm.hostname = "centos-example.com"
    nodo1.vm.network "public_network", bridge: "enp2s0", ip: "172.16.20.132",     use_dhcp_assigned_default_route: true
    nodo1.vm.provision "shell",
      path: "provision.sh",
      env: {"BRANCH" => ENV['BRANCH'],
            "CENTOS_IP" => ENV['CENTOS_IP'],
            "MODE" => ENV['MODE']}
    nodo1.vm.provider "virtualbox" do |vb|
      vb.name = "Centos-SelfHosted"
      vb.memory = "1024"
      vb.cpus = "1"
    end
    nodo1.vm.synced_folder '/home/ftsinfra/ominicontacto', '/vagrant'
  end
end
