#! /bin/sh
#
# asterisk
#
# chkconfig: - 90 10

# Source function library.
. /etc/rc.d/init.d/functions

RETVAL=0
USER=omnileads
GROUP=omnileads
CMD=/opt/asterisk-13/sbin/asterisk

# $ wget http://downloads.asterisk.org/pub/telephony/asterisk/asterisk-13-current.tar.gz
# $ tar xzf asterisk-13-current.tar.gz 
# $ cd asterisk-13.9.0/
# $ ./configure --prefix=/opt/asterisk-13
# $ make -j2
# $ make install
# $ make samples

# See how we were called.
case "$1" in
  start)
        echo -n "Starting asterisk-13... "
        $CMD -U $USER -G $GROUP -g
        RETVAL=$?
        if [ $RETVAL -eq 0 ]
        then
                echo_success
        else
                echo_failure
        fi
        echo
        ;;
  stop)
        echo -n "Stopping asterisk-13... "
        su -l -s /bin/bash -c "$CMD -x 'core stop now'" $USER
        RETVAL=$?
        if [ $RETVAL -eq 0 ]
        then
                echo_success
        else
                echo_failure
        fi
        echo
        ;;
  reload)
        echo -n "Reloading asterisk-13... "
        su -l -s /bin/bash -c "$CMD -x 'core restart gracefully'" $USER
        RETVAL=$?
        if [ $RETVAL -eq 0 ]
        then
                echo_success
        else
                echo_failure
        fi
        echo
        ;;
  status)
        echo -n "Asterisk 11 - Llamadas en curso:"
        su -l -s /bin/bash -c "$CMD -x 'core show calls'" $USER
        RETVAL=$?
        if [ $RETVAL -eq 0 ]
        then
                echo_success
        else
                echo_failure
        fi
        echo
        ;;
  *)
        echo "Usage: $0 start|stop"
        exit 1
esac

exit $RETVAL
