# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-05-13 15:06
from __future__ import unicode_literals

from django.db import migrations

from rest_framework.authtoken.models import Token
from ominicontacto_app.models import User


def adicionar_tokens_usuarios(apps, schema_editor):
    for user in User.objects.all():
        Token.objects.create(user=user)


def eliminar_tokens_usuarios(apps, schema_editor):
    Token.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
    ]

    operations = [
        migrations.RunPython(adicionar_tokens_usuarios, eliminar_tokens_usuarios),
    ]
