# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
---

- debug: msg="Asterisk {{ asterisk_version }} is not installed, proceeding to install"
  when: asterisk_installed.stdout != asterisk_version and asterisk_host is not defined
  tags: ['asterisk','postinstall']

- debug: msg="Asterisk is already installed in version {{ asterisk_version }}, skipping installation steps"
  when: asterisk_installed.stdout == asterisk_version and asterisk_host is not defined
  tags: ['asterisk','postinstall']

- name: Install asterisk-{{ asterisk_version }} package (from s3 source)
  command: yum install -y {{ asterisk_package }}
  when: asterisk_installed.stdout != asterisk_version and asterisk_host is not defined
  tags: postinstall
  retries: 3
  delay: 3
  register: s3_download
  until: s3_download is success

- include: configuration.yml
  tags: asterisk
