# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-06-08 18:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTroncal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PatronDeDiscado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepend', models.PositiveIntegerField(blank=True)),
                ('prefix', models.PositiveIntegerField(blank=True)),
                ('match_pattern', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[\\w]+$')])),
            ],
        ),
        migrations.CreateModel(
            name='RutaSaliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, unique=True, validators=[django.core.validators.RegexValidator('^[ \\w\xe1\xe9\xed\xf3\xfa\xc1\xc9\xcd\xd3\xda\xe0\xe8\xec\xf2\xf9\xc0\xc8\xcc\xd2\xd9\xe2\xea\xee\xf4\xfb\xc2\xca\xce\xd4\xdb\xe4\xeb\xef\xf6\xfc\xc4\xcb\xcf\xd6\xdc\xe7\xc7-]+$')])),
                ('ring_time', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3600), django.core.validators.MinValueValidator(1)])),
                ('dial_options', models.CharField(max_length=512, validators=[django.core.validators.RegexValidator('^[\\w]+$')])),
            ],
        ),
        migrations.CreateModel(
            name='TroncalSIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, unique=True, validators=[django.core.validators.RegexValidator('^[ \\w\xe1\xe9\xed\xf3\xfa\xc1\xc9\xcd\xd3\xda\xe0\xe8\xec\xf2\xf9\xc0\xc8\xcc\xd2\xd9\xe2\xea\xee\xf4\xfb\xc2\xca\xce\xd4\xdb\xe4\xeb\xef\xf6\xfc\xc4\xcb\xcf\xd6\xdc\xe7\xc7-]+$')])),
                ('canales_maximos', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)])),
                ('caller_id', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[ \\w\xe1\xe9\xed\xf3\xfa\xc1\xc9\xcd\xd3\xda\xe0\xe8\xec\xf2\xf9\xc0\xc8\xcc\xd2\xd9\xe2\xea\xee\xf4\xfb\xc2\xca\xce\xd4\xdb\xe4\xeb\xef\xf6\xfc\xc4\xcb\xcf\xd6\xdc\xe7\xc7-]+$')])),
                ('register_string', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[ \\w\xe1\xe9\xed\xf3\xfa\xc1\xc9\xcd\xd3\xda\xe0\xe8\xec\xf2\xf9\xc0\xc8\xcc\xd2\xd9\xe2\xea\xee\xf4\xfb\xc2\xca\xce\xd4\xdb\xe4\xeb\xef\xf6\xfc\xc4\xcb\xcf\xd6\xdc\xe7\xc7-]+$')])),
                ('text_config', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='patrondediscado',
            name='ruta_saliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrones_de_discado', to='configuracion_telefonia_app.RutaSaliente'),
        ),
        migrations.AddField(
            model_name='ordentroncal',
            name='ruta_saliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secuencia_troncales', to='configuracion_telefonia_app.RutaSaliente'),
        ),
        migrations.AddField(
            model_name='ordentroncal',
            name='troncal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden_en_ruta_saliente', to='configuracion_telefonia_app.TroncalSIP'),
        ),
        migrations.AlterUniqueTogether(
            name='ordentroncal',
            unique_together=set([('orden', 'ruta_saliente')]),
        ),
    ]
