# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-06-26 16:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTroncal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PatronDeDiscado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepend', models.PositiveIntegerField(blank=True, null=True)),
                ('prefix', models.PositiveIntegerField(blank=True, null=True)),
                ('match_pattern', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[\\w|\\.|\\[|\\]|-]+$')])),
                ('orden', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RutaSaliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, unique=True, validators=[django.core.validators.RegexValidator('^[\\w]+$')])),
                ('ring_time', models.PositiveIntegerField(default=25, validators=[django.core.validators.MaxValueValidator(3600), django.core.validators.MinValueValidator(1)])),
                ('dial_options', models.CharField(default='Tt', max_length=512, validators=[django.core.validators.RegexValidator('^[HhKkRrL():MATtWw]+$')])),
            ],
        ),
        migrations.CreateModel(
            name='TroncalSIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, unique=True, validators=[django.core.validators.RegexValidator('^[\\w]+$')])),
                ('canales_maximos', models.PositiveIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('caller_id', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[\\w]+$')])),
                ('register_string', models.CharField(blank=True, max_length=100, null=True)),
                ('text_config', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='patrondediscado',
            name='ruta_saliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrones_de_discado', to='configuracion_telefonia_app.RutaSaliente'),
        ),
        migrations.AddField(
            model_name='ordentroncal',
            name='ruta_saliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secuencia_troncales', to='configuracion_telefonia_app.RutaSaliente'),
        ),
        migrations.AddField(
            model_name='ordentroncal',
            name='troncal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_en_rutas_salientes', to='configuracion_telefonia_app.TroncalSIP'),
        ),
        migrations.AlterUniqueTogether(
            name='patrondediscado',
            unique_together=set([('orden', 'ruta_saliente')]),
        ),
        migrations.AlterUniqueTogether(
            name='ordentroncal',
            unique_together=set([('orden', 'ruta_saliente')]),
        ),
    ]
