# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-08-06 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_telefonia_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivr',
            name='audio_principal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='audio_principal_ivrs', to='ominicontacto_app.ArchivoDeAudio'),
            preserve_default=False,
        ),
    ]
