# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-08-06 22:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_telefonia_app', '0002_auto_20180806_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrondediscado',
            name='prefix',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator('^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='patrondediscado',
            name='prepend',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator('^\\d+$')]),
        ),
    ]
