# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-11-26 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_telefonia_app', '0002_hangup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinoentrante',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Campa\xf1a entrante'), (2, 'Validaci\xf3n de fecha/hora'), (3, 'IVR'), (5, 'HangUp')]),
        ),
    ]
