# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-15 18:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_telefonia_app', '0003_attr_hangup_dest_entrante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupohorario',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='troncalsip',
            name='caller_id',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[\\w]+$')], verbose_name='Caller id'),
        ),
        migrations.AlterField(
            model_name='troncalsip',
            name='canales_maximos',
            field=models.PositiveIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Canales m\xe1ximos'),
        ),
        migrations.AlterField(
            model_name='troncalsip',
            name='nombre',
            field=models.CharField(max_length=128, unique=True, validators=[django.core.validators.RegexValidator('^[\\w]+$')], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='troncalsip',
            name='register_string',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Register string'),
        ),
        migrations.AlterField(
            model_name='troncalsip',
            name='text_config',
            field=models.TextField(verbose_name='Text config'),
        ),
        migrations.AlterField(
            model_name='validacionfechahora',
            name='grupo_horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validaciones_fecha_hora', to='configuracion_telefonia_app.GrupoHorario', verbose_name='Grupo horario'),
        ),
        migrations.AlterField(
            model_name='validacionfechahora',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
    ]
