# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-06-10 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_telefonia_app', '0006_identificacion_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinoentrante',
            name='nombre',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='destinoentrante',
            unique_together=set([('tipo', 'object_id')]),
        ),
    ]
