# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-01-23 14:22
from __future__ import unicode_literals

import configuracion_telefonia_app.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_telefonia_app', '0010_auto_20191203_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicaDeEspera',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(
                    max_length=100, unique=True,
                    validators=[django.core.validators.RegexValidator('^[\\w]+$')],
                    verbose_name='Nombre')),
                ('audio_original', models.FileField(
                    blank=True, null=True,
                    upload_to=configuracion_telefonia_app.models.upload_to_musicas_originales)),
                ('audio_asterisk', models.FileField(
                    blank=True, null=True,
                    upload_to=configuracion_telefonia_app.models.upload_to_musicas_asterisk)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(
                    max_length=50, unique=True,
                    validators=[django.core.validators.RegexValidator('^[\\w]+$')],
                    verbose_name='Nombre')),
            ],
        ),
        migrations.AddField(
            model_name='musicadeespera',
            name='playlist',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='musicas',
                to='configuracion_telefonia_app.Playlist'),
        ),
    ]
