# Generated by Django 2.2.7 on 2021-01-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_telefonia_app', '0011_playlist_musica_de_espera'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmdConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_silence', models.PositiveIntegerField(default=2500)),
                ('greeting', models.PositiveIntegerField(default=1500)),
                ('after_greeting_silence', models.PositiveIntegerField(default=800)),
                ('total_analysis_time', models.PositiveIntegerField(default=5000)),
                ('min_word_length', models.PositiveIntegerField(default=100)),
                ('between_words_silence', models.PositiveIntegerField(default=50)),
                ('maximum_number_of_words', models.PositiveIntegerField(default=3)),
                ('maximum_word_length', models.PositiveIntegerField(default=5000)),
                ('silence_threshold', models.PositiveIntegerField(default=256)),
            ],
        ),
    ]
