# Generated by Django 2.2.7 on 2021-01-19 21:10

from django.db import migrations

def adicionar_configuracion_inicial_amd(apps, schema_editor):
    """
    Adiciona la instancia que guarda la configuración AMD del sistema
    """
    AmdConf = apps.get_model("configuracion_telefonia_app", "AmdConf")

    AmdConf.objects.get_or_create(pk=1)

class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_telefonia_app', '0012_amdconf'),
    ]

    operations = [
        migrations.RunPython(adicionar_configuracion_inicial_amd, reverse_code=migrations.RunPython.noop),
    ]
