# Generated by Django 2.2.7 on 2021-01-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_telefonia_app', '0013_crea_amdconf_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsquemaGrabaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contacto', models.BooleanField(default=False)),
                ('fecha', models.BooleanField(default=False)),
                ('telefono_contacto', models.BooleanField(default=False)),
                ('id_campana', models.BooleanField(default=False)),
                ('id_externo_contacto', models.BooleanField(default=False)),
                ('id_externo_campana', models.BooleanField(default=False)),
                ('id_agente', models.BooleanField(default=False)),
            ],
        ),
    ]
