# Generated by Django 2.2.7 on 2021-04-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_telefonia_app', '0015_crea_esquema_grabaciones_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudiosAsteriskConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paquete_idioma', models.CharField(choices=[('es', 'Español'), ('en', 'Inglés'), ('fr', 'Francés'), ('it', 'Italiano'), ('ja', 'Japonés'), ('ru', 'Ruso'), ('sv', 'Sueco')], help_text='Paquete de idioma', max_length=2)),
                ('esta_instalado', models.BooleanField(default=False)),
            ],
        ),
    ]
