# Generated by Django 2.2.7 on 2021-10-07 19:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_telefonia_app', '0016_audiosasteriskconf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrondediscado',
            name='prepend',
            field=models.CharField(
                blank=True, max_length=32, null=True,
                validators=[django.core.validators.RegexValidator('^(#|\\d)+$')]),
        ),
    ]
