# Generated by Django 2.2.7 on 2022-05-17 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_telefonia_app', '0017_patrondediscado_prepend_regex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrondediscado',
            name='match_pattern',
            field=models.CharField(
                max_length=100,
                validators=[django.core.validators.RegexValidator(
                    '^\\+?[\\*\\w|\\.|\\[|\\]|-]+$')]),
        ),
        migrations.AlterField(
            model_name='rutaentrante',
            name='telefono',
            field=models.CharField(
                max_length=30,
                unique=True,
                validators=[django.core.validators.RegexValidator(
                    '^\\+?[\\*\\w|\\.|\\[|\\]|-]+$')]),
        ),
    ]
