# Generated by Django 2.2.7 on 2023-10-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_telefonia_app', '0018_regex_did_entrante_patron_de_discado_saliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinoentrante',
            name='tipo',
            field=models.PositiveIntegerField(choices=[
                (1, 'Campaña entrante'),
                (2, 'Validación de fecha/hora'),
                (3, 'IVR'),
                (5, 'HangUp'),
                (9, 'Identificador cliente'),
                (7, 'Destino personalizado'),
                (10, 'Menú Interactivo de Whatsapp')]),
        ),
    ]
