# Generated by Django 3.2.19 on 2024-08-07 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_telefonia_app', '0019_tipo_destino_entrante_menuwhatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrondediscado',
            name='match_pattern',
            field=models.CharField(
                max_length=100,
                validators=[django.core.validators.RegexValidator(
                    '^(\\.|-|\\+|\\*|#|\\d|\\[|\\]|[XZN])+$')]),
        ),
        migrations.AlterField(
            model_name='patrondediscado',
            name='prefix',
            field=models.CharField(
                blank=True, max_length=32, null=True,
                validators=[django.core.validators.RegexValidator('^(\\+|\\*|#|\\d)+$')]),
        ),
        migrations.AlterField(
            model_name='patrondediscado',
            name='prepend',
            field=models.CharField(
                blank=True, max_length=32, null=True,
                validators=[django.core.validators.RegexValidator('^(\\+|\\*|#|\\d)+$')]),
        ),
    ]
