# Generated by Django 3.2.19 on 2025-09-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_telefonia_app', '0022_ruta_entrante_con_idioma_asterisk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinoentrante',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Campaña entrante'), (2, 'Validación de fecha/hora'), (3, 'IVR'), (5, 'HangUp'), (9, 'Identificador cliente'), (7, 'Destino personalizado'), (10, 'Menú Interactivo de Whatsapp'), (11, 'Agente'), (12, 'Mensaje de Cierre')]),
        ),
    ]
