# Generated by Django 3.2.19 on 2025-12-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_telefonia_app', '0023_alter_destinoentrante_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinoentrante',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Campaña entrante'), (2, 'Validación de fecha/hora'), (3, 'IVR'), (5, 'HangUp'), (9, 'Identificador cliente'), (7, 'Destino personalizado'), (10, 'Menú Interactivo de Whatsapp'), (11, 'Agente'), (12, 'Mensaje de Cierre'), (13, 'Menú Interactivo de Messenger Meta App')]),
        ),
    ]
