# Generated by Django 3.2.19 on 2026-02-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_telefonia_app', '0024_alter_destinoentrante_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificadorcliente',
            name='url',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Url servicio identificación'),
        ),
    ]
